# syntax=dhi.io/build:2-helm3

name: Prometheus Helm chart 28.x
image: dhi.io/prometheus-chart
variant: helm
tags:
  - 28.9.1
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_CHART_REFERENCE: dhi/alertmanager-chart:1.33.1@sha256:d36467dcc86a86cc2c9afaff4e1bc13ceb90d3dcc7d90b33a5f971ab29855293
  CHART_COMMIT_SHA: dd711a4a7e0a384c3003c1eab7dd0946540e47c5
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.1.0@sha256:5bdd8744510d5beb285bea8e4bb84fca81b2a35c02bccb645e3370b2e190ec83
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.51.1@sha256:0df3e30c57b8701510929fbf9d6c1aebe951926e49fa2e58fc058a496afa10bd
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2d5cb7f61093b680ce65cd6b35ed16337c237f5ebc95b32b09cd9a91a0b1f995
  PROMETHEUS_REFERENCE: dhi/prometheus:3.9.1-debian13@sha256:78202bf89773ab29efec2abb24ad40c1136030c09fce22366a5710c7e37cbf0b
  PUSHGATEWAY_CHART_REFERENCE: dhi/pushgateway-chart:3.6.0@sha256:113889e5c70f630945278de228407fb84a4dd091b07baff36dfd1b76c9cbf495
  SEMVER_MAJOR_MINOR_VERSION: "28.9"
  SEMVER_MAJOR_VERSION: "28"
  SEMVER_VERSION: 28.9.1
  VERSION: 28.9.1
contents:
  builds:
    - name: prometheus-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-28.9.1
            checksum: dd711a4a7e0a384c3003c1eab7dd0946540e47c5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            chart:
              appRef: prometheus
              dependencies:
                - alias: alertmanager
                  condition: alertmanager.enabled
                  name: alertmanager
                  ref: dhi/alertmanager-chart:1.33.1@sha256:d36467dcc86a86cc2c9afaff4e1bc13ceb90d3dcc7d90b33a5f971ab29855293
                - alias: kube-state-metrics
                  condition: kube-state-metrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.1.0@sha256:5bdd8744510d5beb285bea8e4bb84fca81b2a35c02bccb645e3370b2e190ec83
                - alias: prometheus-node-exporter
                  condition: prometheus-node-exporter.enabled
                  name: prometheus-node-exporter
                  ref: dhi/node-exporter-chart:4.51.1@sha256:0df3e30c57b8701510929fbf9d6c1aebe951926e49fa2e58fc058a496afa10bd
                - alias: prometheus-pushgateway
                  condition: prometheus-pushgateway.enabled
                  name: prometheus-pushgateway
                  ref: dhi/pushgateway-chart:3.6.0@sha256:113889e5c70f630945278de228407fb84a4dd091b07baff36dfd1b76c9cbf495
              description: Docker Hardened Images Helm chart for Prometheus
              images:
                - name: prometheus
                  ref: dhi/prometheus:3.9.1-debian13@sha256:78202bf89773ab29efec2abb24ad40c1136030c09fce22366a5710c7e37cbf0b
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2d5cb7f61093b680ce65cd6b35ed16337c237f5ebc95b32b09cd9a91a0b1f995
              name: prometheus-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus/config
