metadata:
  display-name: Thanos Helm Chart
  short-description: Thanos is a highly available metrics system that offers long term storage capabilities.
  featured: false
  home-url: https://thanos.io/
  categories:
    - databases-and-storage
    - monitoring-and-observability
