# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Alerts Helm chart 0.x
image: dhi.io/victoriametrics-alert-chart
variant: helm
tags:
  - 0.29.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.30.1-debian13@sha256:2057993681fd6bdff1bb7e8e8397fcc6bfed477e813ea0148b01e48fe62fc5b2
  CHART_COMMIT_SHA: fe149b12908348a67e251d544d619c6e6ead13a9
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
  SEMVER_MAJOR_MINOR_VERSION: "0.29"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.29.0
  VERSION: 0.29.0
  VMALERT_REFERENCE: dhi/victoriametrics-vmalert:1.133.0-debian13@sha256:c5b305d097dccd13660d303f21c2a206e922f401f6bc695796fbfc8a1d62c864
  VMALERT_TAG: 1.129.1
contents:
  builds:
    - name: victoriametrics-alert-chart
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-alert-0.29.0
            checksum: fe149b12908348a67e251d544d619c6e6ead13a9
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            chart:
              appRef: victoriametrics-vmalert
              description: Docker Hardened Images Helm chart for VictoriaMetrics Alert
              images:
                - name: victoriametrics-vmalert
                  ref: dhi/victoriametrics-vmalert:1.133.0-debian13@sha256:c5b305d097dccd13660d303f21c2a206e922f401f6bc695796fbfc8a1d62c864
                - name: alertmanager
                  ref: dhi/alertmanager:0.30.1-debian13@sha256:2057993681fd6bdff1bb7e8e8397fcc6bfed477e813ea0148b01e48fe62fc5b2
              name: victoriametrics-alert-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-alert
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-alert/config
