# syntax=dhi.io/build:1-helm3

name: VictoriaMetrics Alerts Helm chart 0.x
image: dhi.io/victoriametrics-alert-chart
variant: helm
tags:
  - 0.28.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.30.0-debian13@sha256:ab64a18294e008fcafedb8fe0d7cc278a5c9f9042f2dd5dd3c52ae262aef0bc4
  CHART_COMMIT_SHA: edbb837a44bd36c22b1e9f1afeb245eda7426652
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  SEMVER_MAJOR_MINOR_VERSION: "0.28"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.28.0
  VERSION: 0.28.0
  VMALERT_REFERENCE: dhi/victoriametrics-vmalert:1.132.0-debian13@sha256:affabacb78419686029dbeef7b1a2d62490bb96e60dbdddda286d6b6c78bb5fa
  VMALERT_TAG: 1.129.1
contents:
  builds:
    - name: victoriametrics-alert-chart
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-alert-0.28.0
            checksum: edbb837a44bd36c22b1e9f1afeb245eda7426652
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            chart:
              appRef: victoriametrics-vmalert
              description: Docker Hardened Images Helm chart for VictoriaMetrics Alert
              images:
                - name: victoriametrics-vmalert
                  ref: dhi/victoriametrics-vmalert:1.132.0-debian13@sha256:affabacb78419686029dbeef7b1a2d62490bb96e60dbdddda286d6b6c78bb5fa
                - name: alertmanager
                  ref: dhi/alertmanager:0.30.0-debian13@sha256:ab64a18294e008fcafedb8fe0d7cc278a5c9f9042f2dd5dd3c52ae262aef0bc4
              name: victoriametrics-alert-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-alert
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-alert/config
tests:
  - name: Run victoriametrics-alert testcontainers helm tests
    directory: chart/victoriametrics-alert/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
