image:
  registry: ${promtail.registry}
  repository: ${promtail.repository}
  tag: ${promtail.tag}@${promtail.digest}

sidecar:
  configReloader:
    image:
      registry: ${prometheus-config-reloader.registry}
      repository: ${prometheus-config-reloader.repository}
      tag: ${prometheus-config-reloader.tag}@${prometheus-config-reloader.digest}

defaultVolumes:
  - name: run
    emptyDir: {}
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
  - name: pods
    hostPath:
      path: /var/log/pods

podSecurityContext:
  fsGroup: 65532
  runAsUser: 65532
  runAsNonRoot: true
  runAsGroup: 65532
