metadata:
  display-name: OpenTelemetry Collector Helm chart
  short-description: OpenTelemetry Collector is a vendor-agnostic telemetry pipeline that receives, processes, and exports traces, metrics and logs. It is used as a standalone gateway or as an agent to centralize telemetry collection and forward data to backends such as Prometheus, Tempo, Jaeger, or commercial APMs.
  featured: false
  home-url: https://opentelemetry.io
  categories:
    - developer-tools
    - monitoring-and-observability
