metadata:
  display-name: Strimzi Kafka Operator Helm chart
  short-description: A Kubernetes operator that provides a way to run an Apache Kafka cluster on Kubernetes
  featured: false
  home-url: https://strimzi.io/
  categories:
    - message-queues
