# syntax=dhi.io/build:2-helm3

name: CloudNativePG Helm chart 0.x
image: dhi.io/cloudnative-pg-chart
variant: helm
tags:
  - 0.27.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 298d07bda7e9d772a4136f75dea03af81ef44968
  CLOUDNATIVE_PG_REFERENCE: dhi/cloudnative-pg:1.27.2-debian13@sha256:bc521b2eb9939dc033e934cd37cba56e62df994b6fc287325d0e2798be277cf9
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
  SEMVER_MAJOR_MINOR_VERSION: "0.27"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.27.0
  VERSION: 0.27.0
contents:
  builds:
    - name: cloudnative-pg
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/cloudnative-pg/charts.git#cloudnative-pg-v0.27.0
            checksum: 298d07bda7e9d772a4136f75dea03af81ef44968
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/cloudnative-pg
          with:
            chart:
              appRef: cloudnative-pg
              description: Docker Hardened Images Helm chart for CloudNativePG
              images:
                - name: cloudnative-pg
                  ref: dhi/cloudnative-pg:1.27.2-debian13@sha256:bc521b2eb9939dc033e934cd37cba56e62df994b6fc287325d0e2798be277cf9
              name: cloudnative-pg-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cloudnative-pg/charts
              version: 0.27.0
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/cloudnative-pg
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/cloudnative-pg
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: cloudnative-pg
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: cloudnative-pg
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cloudnative-pg/config
