# syntax=dhi.io/build:2-helm3

name: CloudNativePG Helm chart 0.x
image: dhi.io/cloudnative-pg-chart
variant: helm
tags:
  - 0.27.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 3c56d04ef8d657991d3760ea96c4c71702fb597c
  CLOUDNATIVE_PG_REFERENCE: dhi/cloudnative-pg:1.27.3-debian13@sha256:5fec7dc05040e88a4cc9fe9257c58f30f77394bdcd1f71cb6bed874d15e99bfe
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
  SEMVER_MAJOR_MINOR_VERSION: "0.27"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.27.1
  VERSION: 0.27.1
contents:
  builds:
    - name: cloudnative-pg
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/cloudnative-pg/charts.git#cloudnative-pg-v0.27.1
            checksum: 3c56d04ef8d657991d3760ea96c4c71702fb597c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/cloudnative-pg
          with:
            chart:
              appRef: cloudnative-pg
              description: Docker Hardened Images Helm chart for CloudNativePG
              images:
                - name: cloudnative-pg
                  ref: dhi/cloudnative-pg:1.27.3-debian13@sha256:5fec7dc05040e88a4cc9fe9257c58f30f77394bdcd1f71cb6bed874d15e99bfe
              name: cloudnative-pg-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cloudnative-pg/charts
              version: 0.27.1
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/cloudnative-pg
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/cloudnative-pg
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: cloudnative-pg
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: cloudnative-pg
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cloudnative-pg/config
