# syntax=dhi.io/build:1-helm3

name: CloudNativePG Helm chart 0.x
image: dhi.io/cloudnative-pg-chart
variant: helm
tags:
  - 0.27.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 298d07bda7e9d772a4136f75dea03af81ef44968
  CLOUDNATIVE_PG_REFERENCE: dhi/cloudnative-pg:1.27.2-debian13@sha256:6ae894b345d0e560f21322527deb59d0052715d98c0bece963423315f68f7af5
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  SEMVER_MAJOR_MINOR_VERSION: "0.27"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.27.0
  VERSION: 0.27.0
contents:
  builds:
    - name: cloudnative-pg
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/cloudnative-pg/charts.git#cloudnative-pg-v0.27.0
            checksum: 298d07bda7e9d772a4136f75dea03af81ef44968
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/cloudnative-pg
          with:
            chart:
              appRef: cloudnative-pg
              description: Docker Hardened Images Helm chart for CloudNativePG
              images:
                - name: cloudnative-pg
                  ref: dhi/cloudnative-pg:1.27.2-debian13@sha256:6ae894b345d0e560f21322527deb59d0052715d98c0bece963423315f68f7af5
              name: cloudnative-pg-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cloudnative-pg/charts
              version: 0.27.0
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/cloudnative-pg
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/cloudnative-pg
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: cloudnative-pg
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: cloudnative-pg
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cloudnative-pg/config
tests:
  - name: Run cloudnative-pg testcontainers helm tests
    directory: chart/cloudnative-pg/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
