# syntax=dhi.io/build:2-debian13

name: Prometheus NATS Exporter 0.18.x (dev)
image: dhi.io/prometheus-nats-exporter
variant: dev
tags:
  - 0-dev
  - 0.18-dev
  - 0.18.0-dev
  - 0-debian13-dev
  - 0.18-debian13-dev
  - 0.18.0-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-11-21"
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: d161758f7bc0f2af7e0bdf007db80e52413d795c
  GO_REFERENCE: dhi/golang:1.25.6-debian13-dev@sha256:a0607a787c801dba5f5637b939566066da29bebc0e6512e3fa0af1695c5090bc
  SEMVER_MAJOR_MINOR_VERSION: "0.18"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.18.0
  VERSION: 0.18.0
contents:
  packages:
    - '!base-files'
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - util-linux
  builds:
    - name: prometheus-nats-exporter
      uses: dhi.io/golang:1.25.6-debian13-dev@sha256:a0607a787c801dba5f5637b939566066da29bebc0e6512e3fa0af1695c5090bc
      caches:
        - path: /go/pkg/mod
      contents:
        files:
          - url: git+https://github.com/nats-io/prometheus-nats-exporter.git#v0.18.0
            checksum: d161758f7bc0f2af7e0bdf007db80e52413d795c
            path: /go/src/github.com/nats-io/prometheus-nats-exporter
            spdx:
              name: prometheus-nats-exporter
              version: 0.18.0
              packages:
                - name: prometheus-nats-exporter
                  purl: pkg:golang/github.com/nats-io/prometheus-nats-exporter@v0.18.0
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/nats-io/prometheus-nats-exporter
          with:
            deps: []
            download: true
        - name: test
          work-dir: /go/src/github.com/nats-io/prometheus-nats-exporter
          privileged: true
          runs: |
            set -eux -o pipefail

            if [ "${target.fips}" = "true" ]; then
              # Unit tests are not FIPS compliant. Will try to exercise X25519 which is not allowed in FIPS mode.
              export GODEBUG=fips140=on
            fi
            CGO_ENABLED=0 go test ./test/...
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/nats-io/prometheus-nats-exporter
          with:
            ldflags:
              - -s -w
              - -X main.version=0.18.0
              - -X main.commit=d161758f7bc0f2af7e0bdf007db80e52413d795c
              - -X main.date=$(date -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/local/bin/prometheus-nats-exporter
            packages: .
      outputs:
        - source: ${target.dir}/usr/local/bin/prometheus-nats-exporter
          target: /usr/local/bin/prometheus-nats-exporter
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/prometheus-nats-exporter
          target: /opt/docker/sbom/prometheus-nats-exporter
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
environment:
  DEBIAN_FRONTEND: noninteractive
annotations:
  org.opencontainers.image.description: A minimal Prometheus NATS Exporter image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/local/bin/prometheus-nats-exporter
ports:
  - 7777/tcp
