# syntax=dhi.io/build:2-debian13

name: Prometheus NATS Exporter 0.19.x
image: dhi.io/prometheus-nats-exporter
variant: runtime
tags:
  - "0"
  - "0.19"
  - 0.19.1
  - 0-debian13
  - 0.19-debian13
  - 0.19.1-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-11-21"
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: 635496a73745d94ea298133d5e0e16a7ef880019
  GO_REFERENCE: dhi/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
  SEMVER_MAJOR_MINOR_VERSION: "0.19"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.19.1
  VERSION: 0.19.1
contents:
  packages:
    - '!base-files'
  builds:
    - name: prometheus-nats-exporter
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      caches:
        - path: /go/pkg/mod
      contents:
        files:
          - url: git+https://github.com/nats-io/prometheus-nats-exporter.git#v0.19.1
            checksum: 635496a73745d94ea298133d5e0e16a7ef880019
            path: /go/src/github.com/nats-io/prometheus-nats-exporter
            spdx:
              name: prometheus-nats-exporter
              version: 0.19.1
              packages:
                - name: prometheus-nats-exporter
                  purl: pkg:golang/github.com/nats-io/prometheus-nats-exporter@v0.19.1
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/nats-io/prometheus-nats-exporter
          with:
            deps: []
            download: true
        - name: test
          work-dir: /go/src/github.com/nats-io/prometheus-nats-exporter
          privileged: true
          runs: |
            set -eux -o pipefail

            if [ "${target.fips}" = "true" ]; then
              # Unit tests are not FIPS compliant. Will try to exercise X25519 which is not allowed in FIPS mode.
              export GODEBUG=fips140=on
            fi
            CGO_ENABLED=0 go test ./test/...
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/nats-io/prometheus-nats-exporter
          with:
            ldflags:
              - -s -w
              - -X main.version=0.19.1
              - -X main.commit=635496a73745d94ea298133d5e0e16a7ef880019
              - -X main.date=$(date -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/local/bin/prometheus-nats-exporter
            packages: .
      outputs:
        - source: ${target.dir}/usr/local/bin/prometheus-nats-exporter
          target: /usr/local/bin/prometheus-nats-exporter
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/prometheus-nats-exporter
          target: /opt/docker/sbom/prometheus-nats-exporter
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
annotations:
  org.opencontainers.image.description: A minimal Prometheus NATS Exporter image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/local/bin/prometheus-nats-exporter
ports:
  - 7777/tcp
