metadata:
  display-name: Promtail Helm chart
  short-description: Agent which ships the contents of local logs to a private Grafana Loki instance or Grafana Cloud.
  featured: false
  home-url: https://grafana.com/docs/loki/latest/send-data/promtail/
  categories:
    - developer-tools
    - monitoring-and-observability
