# syntax=dhi.io/build:2-helm3

name: Strimzi Kafka Operator Helm chart 0.x
image: dhi.io/strimzi-kafka-operator-chart
variant: helm
tags:
  - 0.1.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: eb359e808dee4f00230ed031bd381cd2a2f94b9c
  CHART_VERSION: 0.1.1
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
  SEMVER_MAJOR_MINOR_VERSION: "0.49"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.49.1
  STRIMZI_KAFKA_REFERENCE: dhi/strimzi-kafka:0.49.1-debian13-kafka-4.1.1@sha256:69abd32b3a193b80e12928242adedc935fe1306db079087dcfccc9caf937a478
  STRIMZI_OPERATOR_REFERENCE: dhi/strimzi-operator:0.49.1-debian13@sha256:6e55de5f5899aa6c8fac91cdf1d6a16771be3e2b36c1a4941839eb2f18a763fe
  VERSION: 0.49.1
contents:
  builds:
    - name: strimzi-kafka-operator
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/strimzi/strimzi-kafka-operator.git#0.49.1
            checksum: eb359e808dee4f00230ed031bd381cd2a2f94b9c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            chart:
              appRef: strimzi-operator
              description: Docker Hardened Images Helm chart for Strimzi Kafka Operator
              images:
                - name: strimzi-operator
                  ref: dhi/strimzi-operator:0.49.1-debian13@sha256:6e55de5f5899aa6c8fac91cdf1d6a16771be3e2b36c1a4941839eb2f18a763fe
                - name: strimzi-kafka
                  ref: dhi/strimzi-kafka:0.49.1-debian13-kafka-4.1.1@sha256:69abd32b3a193b80e12928242adedc935fe1306db079087dcfccc9caf937a478
              name: strimzi-kafka-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/strimzi/strimzi-kafka-operator
              version: 0.1.1
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/strimzi-kafka-operator/config
