# syntax=dhi.io/build:2-helm3

name: Strimzi Kafka Operator Helm chart 0.x
image: dhi.io/strimzi-kafka-operator-chart
variant: helm
tags:
  - 0.1.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 825447910afa6e2db8f2897c4ada35dba9dcfa2a
  CHART_VERSION: 0.1.1
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
  SEMVER_MAJOR_MINOR_VERSION: "0.50"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.50.0
  STRIMZI_KAFKA_REFERENCE: dhi/strimzi-kafka:0.50.0-debian13-kafka-4.1.1@sha256:67c678b08175657c73b6ea4c02d018805899e23c92bfb88ed5534fbe421c3eab
  STRIMZI_OPERATOR_REFERENCE: dhi/strimzi-operator:0.50.0-debian13@sha256:5915aeda7da71293def3542f97c654bd46dd78af10204c86982cca2d84ce0477
  VERSION: 0.50.0
contents:
  builds:
    - name: strimzi-kafka-operator
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/strimzi/strimzi-kafka-operator.git#0.50.0
            checksum: 825447910afa6e2db8f2897c4ada35dba9dcfa2a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            chart:
              appRef: strimzi-operator
              description: Docker Hardened Images Helm chart for Strimzi Kafka Operator
              images:
                - name: strimzi-operator
                  ref: dhi/strimzi-operator:0.50.0-debian13@sha256:5915aeda7da71293def3542f97c654bd46dd78af10204c86982cca2d84ce0477
                - name: strimzi-kafka
                  ref: dhi/strimzi-kafka:0.50.0-debian13-kafka-4.1.1@sha256:67c678b08175657c73b6ea4c02d018805899e23c92bfb88ed5534fbe421c3eab
              name: strimzi-kafka-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/strimzi/strimzi-kafka-operator
              version: 0.1.1
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/strimzi-kafka-operator/config
