# syntax=dhi.io/build:2-helm3

name: Strimzi Kafka Operator Helm chart 0.x
image: dhi.io/strimzi-kafka-operator-chart
variant: helm
tags:
  - 0.1.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: eb359e808dee4f00230ed031bd381cd2a2f94b9c
  CHART_VERSION: 0.1.1
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
  SEMVER_MAJOR_MINOR_VERSION: "0.49"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.49.1
  STRIMZI_KAFKA_REFERENCE: dhi/strimzi-kafka:0.49.1-debian13-kafka-4.1.1@sha256:ea17c44ce9edb92bc7acf75777b82c0f154429ec3ee7c666de2643a2b8224cde
  STRIMZI_OPERATOR_REFERENCE: dhi/strimzi-operator:0.49.1-debian13@sha256:df33f7093ec4c730ebe9cb5e4ddf69a4757105cca600eaee48c286e630bac0ef
  VERSION: 0.49.1
contents:
  builds:
    - name: strimzi-kafka-operator
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/strimzi/strimzi-kafka-operator.git#0.49.1
            checksum: eb359e808dee4f00230ed031bd381cd2a2f94b9c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            chart:
              appRef: strimzi-operator
              description: Docker Hardened Images Helm chart for Strimzi Kafka Operator
              images:
                - name: strimzi-operator
                  ref: dhi/strimzi-operator:0.49.1-debian13@sha256:df33f7093ec4c730ebe9cb5e4ddf69a4757105cca600eaee48c286e630bac0ef
                - name: strimzi-kafka
                  ref: dhi/strimzi-kafka:0.49.1-debian13-kafka-4.1.1@sha256:ea17c44ce9edb92bc7acf75777b82c0f154429ec3ee7c666de2643a2b8224cde
              name: strimzi-kafka-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/strimzi/strimzi-kafka-operator
              version: 0.1.1
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/strimzi-kafka-operator/config
