# syntax=dhi.io/build:2-debian13

name: Grafana 11.6.x (dev)
image: dhi.io/grafana
variant: dev
tags:
  - 11-dev
  - 11.6-dev
  - 11.6.10-dev
  - 11-debian13-dev
  - 11.6-debian13-dev
  - 11.6.10-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-03-25"
  end-of-life: "2026-06-25"
vars:
  COMMIT_SHA: b0865c0373937d9758e189c7047de975899f9de0
  GO_REFERENCE: dhi/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
  GO_VERSION: 1.25.7
  NODE_REFERENCE: dhi/node:22.22.0-debian13-dev@sha256:50357af85ac21065acba83877601749772a229ad8234082c81d34a22a5a4a81b
  NODE_VERSION: 22.22.0
  PYTHON_REFERENCE: dhi/python:3.13.12-debian13-dev@sha256:fb4baa0ca0211b20cb45e8fcf2509542b4b1ca634dde7f888027c19a39f30299
  PYTHON_VERSION: 3.13.12
  SEMVER_MAJOR_MINOR_VERSION: "11.6"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.6.10
  VERSION: 11.6.10
contents:
  packages:
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - base-files
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - tar
    - util-linux
  builds:
    - name: grafana
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      contents:
        packages:
          - sed
          - grep
          - make
          - build-essential
          - python3-setuptools
          - grep
          - gcc
          - jq
        files:
          - url: git+https://github.com/grafana/grafana.git#v11.6.10
            checksum: b0865c0373937d9758e189c7047de975899f9de0
            path: /go/src/github.com/grafana/grafana
            spdx:
              name: grafana
              version: 11.6.10
              packages:
                - name: grafana
                  purl: pkg:dhi/grafana@11.6.10
                  license: AGPL-3.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:22.22.0-debian13-dev@sha256:50357af85ac21065acba83877601749772a229ad8234082c81d34a22a5a4a81b
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
          - name: dhi.io/python:3.13.12-debian13-dev@sha256:fb4baa0ca0211b20cb45e8fcf2509542b4b1ca634dde7f888027c19a39f30299
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
      pipeline:
        - name: update version
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            # The tagged source contains an old version in package.json
            sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"11.6.10\"/g" package.json
        - name: update node-gyp
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            # Update node-gyp version to be compatible with Python >=3.12
            jq '.resolutions += { "node-gyp" : "^10.0.0" }' package.json > package.new.json
            rm package.json
            mv package.new.json package.json

            # Update lockfile with updated versions
            yarn install
        - name: build ui
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            export NODE_OPTIONS=--max_old_space_size=8000
            yarn install --immutable

            export NODE_ENV=production
            yarn build

            mkdir -p "${target.dir}/usr/share/grafana/public/"
            cp -r public/* "${target.dir}/usr/share/grafana/public/"
        - name: update go dependencies 11.6
          uses: go/bump@v1
          work-dir: /go/src/github.com/grafana/grafana
          with:
            deps:
              - github.com/golang-jwt/jwt/v4@v4.5.2
              - github.com/cloudflare/circl@v1.6.1
              - github.com/go-viper/mapstructure/v2@v2.4.0
              - golang.org/x/crypto@v0.45.0
            downgrade: true
            replaces:
              - github.com/getkin/kin-openapi=github.com/getkin/kin-openapi@v0.131.0
            work-replaces:
              - github.com/getkin/kin-openapi=github.com/getkin/kin-openapi@v0.131.0
        - name: compile
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            make build-go
        - name: install
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            mkdir -p "${target.dir}/usr/share/grafana/bin/"
            cp ./bin/*/grafana* "${target.dir}/usr/share/grafana/bin/"

            mkdir -p "${target.dir}/etc/grafana/"
            cp conf/sample.ini "${target.dir}/etc/grafana/grafana.ini"
            cp conf/ldap.toml "${target.dir}/etc/grafana/ldap.toml"

            mkdir -p "${target.dir}/usr/share/grafana/conf/"
            cp -r conf/* "${target.dir}/usr/share/grafana/conf/"
      outputs:
        - source: ${target.dir}/usr/share/grafana/public
          target: /usr/share/grafana/public
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/bin
          target: /usr/share/grafana/bin
          uid: 0
          gid: 0
        - source: ${target.dir}/etc/grafana
          target: /etc/grafana
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/conf
          target: /usr/share/grafana/conf
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/grafana
          target: /opt/docker/sbom/grafana
          uid: 0
          gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: grafana
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: grafana
      gid: 65532
      members:
        - grafana
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /var/lib/grafana
environment:
  DEBIAN_FRONTEND: noninteractive
  GRAFANA_VERSION: 11.6.10
  PATH: /usr/share/grafana/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin
paths:
  - type: directory
    path: /etc/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/alerting
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/dashboards
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/datasources
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/log/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /tmp
    uid: 65532
    gid: 65532
    mode: "0777"
annotations:
  org.opencontainers.image.description: A minimal Grafana image
  org.opencontainers.image.licenses: AGPL-3.0
entrypoint:
  - grafana
  - server
  - --homepath=/usr/share/grafana
  - --config=/etc/grafana/grafana.ini
  - --packaging=docker
  - cfg:default.log.mode=console
  - cfg:default.paths.data=/var/lib/grafana
  - cfg:default.paths.logs=/var/log/grafana
  - cfg:default.paths.plugins=/var/lib/grafana/plugins
  - cfg:default.paths.provisioning=/etc/grafana/provisioning
ports:
  - 3000/tcp
