# syntax=dhi.io/build:2-debian13

name: Grafana 12.0.x
image: dhi.io/grafana
variant: runtime
tags:
  - "12.0"
  - 12.0.8
  - 12.0-debian13
  - 12.0.8-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-05-05"
  end-of-life: "2026-02-05"
vars:
  COMMIT_SHA: e133492ed413438f6a81cd956c8d7712f83f1579
  GO_REFERENCE: dhi/golang:1.25.6-debian13-dev@sha256:a0607a787c801dba5f5637b939566066da29bebc0e6512e3fa0af1695c5090bc
  GO_VERSION: 1.25.6
  NODE_REFERENCE: dhi/node:22.22.0-debian13-dev@sha256:78c89ee96ad8309a4005d7bae9d2a143f897717ff4b7eca960b2d04d3036e672
  NODE_VERSION: 22.22.0
  PYTHON_REFERENCE: dhi/python:3.13.11-debian13-dev@sha256:0a677bc0abacbc3a89ee5fea616c9a005d79f2ece71ed7424bbb28047dbd930b
  PYTHON_VERSION: 3.13.11
  SEMVER_MAJOR_MINOR_VERSION: "12.0"
  SEMVER_MAJOR_VERSION: "12"
  SEMVER_VERSION: 12.0.8
  VERSION: 12.0.8
contents:
  packages:
    - '!dpkg'
    - '!gawk'
    - '!libelogind0'
    - '!libslang2'
    - '!mawk'
    - '!original-awk'
    - '!tar'
    - base-files
    - ca-certificates
  builds:
    - name: grafana
      uses: dhi.io/golang:1.25.6-debian13-dev@sha256:a0607a787c801dba5f5637b939566066da29bebc0e6512e3fa0af1695c5090bc
      contents:
        packages:
          - sed
          - grep
          - make
          - build-essential
          - python3-setuptools
          - grep
          - gcc
        files:
          - url: git+https://github.com/grafana/grafana.git#v12.0.8
            checksum: e133492ed413438f6a81cd956c8d7712f83f1579
            path: /go/src/github.com/grafana/grafana
            spdx:
              name: grafana
              version: 12.0.8
              packages:
                - name: grafana
                  purl: pkg:dhi/grafana@12.0.8
                  license: AGPL-3.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:22.22.0-debian13-dev@sha256:78c89ee96ad8309a4005d7bae9d2a143f897717ff4b7eca960b2d04d3036e672
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
          - name: dhi.io/python:3.13.11-debian13-dev@sha256:0a677bc0abacbc3a89ee5fea616c9a005d79f2ece71ed7424bbb28047dbd930b
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
      pipeline:
        - name: update version
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            # The tagged source contains an old version in package.json
            sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"12.0.8\"/g" package.json
        - name: build ui
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            export NODE_OPTIONS=--max_old_space_size=8000
            yarn install --immutable

            export NODE_ENV=production
            yarn build

            mkdir -p "${target.dir}/usr/share/grafana/public/"
            cp -r public/* "${target.dir}/usr/share/grafana/public/"
        - name: update go dependencies 12.0
          uses: go/bump@v1
          work-dir: /go/src/github.com/grafana/grafana
          with:
            deps:
              - github.com/cloudflare/circl@v1.6.1
              - github.com/go-viper/mapstructure/v2@v2.4.0
              - golang.org/x/crypto@v0.45.0
            downgrade: true
        - name: compile
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            make build-go
        - name: install
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            mkdir -p "${target.dir}/usr/share/grafana/bin/"
            cp ./bin/*/grafana* "${target.dir}/usr/share/grafana/bin/"

            mkdir -p "${target.dir}/etc/grafana/"
            cp conf/sample.ini "${target.dir}/etc/grafana/grafana.ini"
            cp conf/ldap.toml "${target.dir}/etc/grafana/ldap.toml"

            mkdir -p "${target.dir}/usr/share/grafana/conf/"
            cp -r conf/* "${target.dir}/usr/share/grafana/conf/"
      outputs:
        - source: ${target.dir}/usr/share/grafana/public
          target: /usr/share/grafana/public
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/bin
          target: /usr/share/grafana/bin
          uid: 0
          gid: 0
        - source: ${target.dir}/etc/grafana
          target: /etc/grafana
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/conf
          target: /usr/share/grafana/conf
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/grafana
          target: /opt/docker/sbom/grafana
          uid: 0
          gid: 0
accounts:
  run-as: grafana
  users:
    - name: grafana
      uid: 65532
      gid: 65532
  groups:
    - name: grafana
      gid: 65532
      members:
        - grafana
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /var/lib/grafana
environment:
  GRAFANA_VERSION: 12.0.8
  PATH: /usr/share/grafana/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin
paths:
  - type: directory
    path: /etc/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/alerting
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/dashboards
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/datasources
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/log/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /tmp
    uid: 65532
    gid: 65532
    mode: "0755"
annotations:
  org.opencontainers.image.description: A minimal Grafana image
  org.opencontainers.image.licenses: AGPL-3.0
entrypoint:
  - grafana
  - server
  - --homepath=/usr/share/grafana
  - --config=/etc/grafana/grafana.ini
  - --packaging=docker
  - cfg:default.log.mode=console
  - cfg:default.paths.data=/var/lib/grafana
  - cfg:default.paths.logs=/var/log/grafana
  - cfg:default.paths.plugins=/var/lib/grafana/plugins
  - cfg:default.paths.provisioning=/etc/grafana/provisioning
ports:
  - 3000/tcp
