# syntax=dhi.io/build:2-debian13

name: Grafana 12.2.x (dev)
image: dhi.io/grafana
variant: dev
tags:
  - 12.2-dev
  - 12.2.3-dev
  - 12.2-debian13-dev
  - 12.2.3-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-09-23"
  end-of-life: "2026-06-23"
vars:
  COMMIT_SHA: 33436a3f337ea2f1c44aefa5c5ac508763741340
  GO_REFERENCE: dhi/golang:1.25.6-debian13-dev@sha256:a0607a787c801dba5f5637b939566066da29bebc0e6512e3fa0af1695c5090bc
  GO_VERSION: 1.25.6
  NODE_REFERENCE: dhi/node:22.22.0-debian13-dev@sha256:7391687c0ebc6ddacb1be52bee3c05e19a213f483f87fc6a5fc1af1140aaf283
  NODE_VERSION: 22.22.0
  PYTHON_REFERENCE: dhi/python:3.13.11-debian13-dev@sha256:237e07b4e1db4ea6e20b6471f4bd40c476ab8593e55726e4ef7780748b362bf2
  PYTHON_VERSION: 3.13.11
  RUST_REFERENCE: dhi/rust:1.93.0-debian13@sha256:341eb393e8afb4c8d486555d6919e2e8ed060f6e097b74cd9b702ee805576920
  RUST_VERSION: 1.93.0
  SEMVER_MAJOR_MINOR_VERSION: "12.2"
  SEMVER_MAJOR_VERSION: "12"
  SEMVER_VERSION: 12.2.3
  VERSION: 12.2.3
contents:
  packages:
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - base-files
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - tar
    - util-linux
  builds:
    - name: grafana
      uses: dhi.io/golang:1.25.6-debian13-dev@sha256:a0607a787c801dba5f5637b939566066da29bebc0e6512e3fa0af1695c5090bc
      contents:
        packages:
          - bash
          - sed
          - grep
          - make
          - build-essential
          - python3-setuptools
          - grep
          - gcc
          - chromium
        files:
          - url: git+https://github.com/grafana/grafana.git#v12.2.3
            checksum: 33436a3f337ea2f1c44aefa5c5ac508763741340
            path: /go/src/github.com/grafana/grafana
            spdx:
              name: grafana
              version: 12.2.3
              packages:
                - name: grafana
                  purl: pkg:dhi/grafana@12.2.3
                  license: AGPL-3.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:22.22.0-debian13-dev@sha256:7391687c0ebc6ddacb1be52bee3c05e19a213f483f87fc6a5fc1af1140aaf283
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
          - name: dhi.io/python:3.13.11-debian13-dev@sha256:237e07b4e1db4ea6e20b6471f4bd40c476ab8593e55726e4ef7780748b362bf2
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
          - name: dhi.io/rust:1.93.0-debian13@sha256:341eb393e8afb4c8d486555d6919e2e8ed060f6e097b74cd9b702ee805576920
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
      pipeline:
        - name: update version
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            # The tagged source contains an old version in package.json
            sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"12.2.3\"/g" package.json
        - name: build ui
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            export NODE_OPTIONS=--max_old_space_size=8000
            yarn install --immutable

            export NODE_ENV=production
            yarn build

            mkdir -p "${target.dir}/usr/share/grafana/public/"
            cp -r public/* "${target.dir}/usr/share/grafana/public/"
        - name: update go dependencies 12.2
          uses: go/bump@v1
          work-dir: /go/src/github.com/grafana/grafana
          with:
            deps:
              - golang.org/x/crypto@v0.45.0
            downgrade: true
        - name: compile
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            make build-go
        - name: install
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            mkdir -p "${target.dir}/usr/share/grafana/bin/"
            cp ./bin/*/grafana* "${target.dir}/usr/share/grafana/bin/"

            mkdir -p "${target.dir}/etc/grafana/"
            cp conf/sample.ini "${target.dir}/etc/grafana/grafana.ini"
            cp conf/ldap.toml "${target.dir}/etc/grafana/ldap.toml"

            mkdir -p "${target.dir}/usr/share/grafana/conf/"
            cp -r conf/* "${target.dir}/usr/share/grafana/conf/"
      outputs:
        - source: ${target.dir}/usr/share/grafana/public
          target: /usr/share/grafana/public
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/bin
          target: /usr/share/grafana/bin
          uid: 0
          gid: 0
        - source: ${target.dir}/etc/grafana
          target: /etc/grafana
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/conf
          target: /usr/share/grafana/conf
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/grafana
          target: /opt/docker/sbom/grafana
          uid: 0
          gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: grafana
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: grafana
      gid: 65532
      members:
        - grafana
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /var/lib/grafana
environment:
  DEBIAN_FRONTEND: noninteractive
  GRAFANA_VERSION: 12.2.3
  PATH: /usr/share/grafana/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin
paths:
  - type: directory
    path: /etc/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/alerting
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/dashboards
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/datasources
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/log/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /tmp
    uid: 65532
    gid: 65532
    mode: "0777"
annotations:
  org.opencontainers.image.description: A minimal Grafana image
  org.opencontainers.image.licenses: AGPL-3.0
entrypoint:
  - grafana
  - server
  - --homepath=/usr/share/grafana
  - --config=/etc/grafana/grafana.ini
  - --packaging=docker
  - cfg:default.log.mode=console
  - cfg:default.paths.data=/var/lib/grafana
  - cfg:default.paths.logs=/var/log/grafana
  - cfg:default.paths.plugins=/var/lib/grafana/plugins
  - cfg:default.paths.provisioning=/etc/grafana/provisioning
ports:
  - 3000/tcp
