# syntax=dhi.io/build:2-debian13

name: Grafana 12.3.x (dev)
image: dhi.io/grafana
variant: dev
tags:
  - 12-dev
  - 12.3-dev
  - 12.3.2-dev
  - 12-debian13-dev
  - 12.3-debian13-dev
  - 12.3.2-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-11-18"
  end-of-life: "2026-08-18"
vars:
  COMMIT_SHA: df2547decd50d14defa20ec9ce1c2e2bc9462d72
  GO_REFERENCE: dhi/golang:1.25.6-debian13-dev@sha256:1c001ad95e22efced3c6cc3cf875bbfe69c061a383d3b787d4f0a8103e73311c
  GO_VERSION: 1.25.6
  NODE_REFERENCE: dhi/node:22.22.0-debian13-dev@sha256:992058adf730d1c5f0c03396dd13f4771efc4946777871b3d2ace8803b622223
  NODE_VERSION: 22.22.0
  PYTHON_REFERENCE: dhi/python:3.13.11-debian13-dev@sha256:9781560a0ae891f2830b69d0b3709adb71137ebe601ef02e1b8a06b77e03a92d
  PYTHON_VERSION: 3.13.11
  RUST_REFERENCE: dhi/rust:1.93.0-debian13@sha256:fe475b0245d118aacf5ac365e741535b0fb8ce2e5bf01d9f484ff67680bb964f
  RUST_VERSION: 1.93.0
  SEMVER_MAJOR_MINOR_VERSION: "12.3"
  SEMVER_MAJOR_VERSION: "12"
  SEMVER_VERSION: 12.3.2
  VERSION: 12.3.2
contents:
  packages:
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - base-files
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - tar
    - util-linux
  builds:
    - name: grafana
      uses: dhi.io/golang:1.25.6-debian13-dev@sha256:1c001ad95e22efced3c6cc3cf875bbfe69c061a383d3b787d4f0a8103e73311c
      contents:
        packages:
          - bash
          - sed
          - grep
          - make
          - build-essential
          - python3-setuptools
          - grep
          - gcc
          - chromium
        files:
          - url: git+https://github.com/grafana/grafana.git#v12.3.2
            checksum: df2547decd50d14defa20ec9ce1c2e2bc9462d72
            path: /go/src/github.com/grafana/grafana
            spdx:
              name: grafana
              version: 12.3.2
              packages:
                - name: grafana
                  purl: pkg:dhi/grafana@12.3.2
                  license: AGPL-3.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:22.22.0-debian13-dev@sha256:992058adf730d1c5f0c03396dd13f4771efc4946777871b3d2ace8803b622223
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
          - name: dhi.io/python:3.13.11-debian13-dev@sha256:9781560a0ae891f2830b69d0b3709adb71137ebe601ef02e1b8a06b77e03a92d
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
          - name: dhi.io/rust:1.93.0-debian13@sha256:fe475b0245d118aacf5ac365e741535b0fb8ce2e5bf01d9f484ff67680bb964f
            includes:
              - opt/**
              - usr/local/bin
            uid: 0
            gid: 0
      pipeline:
        - name: update version
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            # The tagged source contains an old version in package.json
            sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"12.3.2\"/g" package.json
        - name: build ui
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            export NODE_OPTIONS=--max_old_space_size=8000
            yarn install --immutable

            export NODE_ENV=production
            yarn build

            mkdir -p "${target.dir}/usr/share/grafana/public/"
            cp -r public/* "${target.dir}/usr/share/grafana/public/"
        - name: update go dependencies 12.2
          uses: go/bump@v1
          work-dir: /go/src/github.com/grafana/grafana
          with:
            deps:
              - golang.org/x/crypto@v0.45.0
              - github.com/openfga/openfga@v1.11.1
            downgrade: true
        - name: compile
          work-dir: /go/src/github.com/grafana/grafana
          privileged: true
          runs: |
            set -eux -o pipefail

            make build-go
        - name: install
          work-dir: /go/src/github.com/grafana/grafana
          runs: |
            set -eux -o pipefail

            mkdir -p "${target.dir}/usr/share/grafana/bin/"
            cp ./bin/*/grafana* "${target.dir}/usr/share/grafana/bin/"

            mkdir -p "${target.dir}/etc/grafana/"
            cp conf/sample.ini "${target.dir}/etc/grafana/grafana.ini"
            cp conf/ldap.toml "${target.dir}/etc/grafana/ldap.toml"

            mkdir -p "${target.dir}/usr/share/grafana/conf/"
            cp -r conf/* "${target.dir}/usr/share/grafana/conf/"
      outputs:
        - source: ${target.dir}/usr/share/grafana/public
          target: /usr/share/grafana/public
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/bin
          target: /usr/share/grafana/bin
          uid: 0
          gid: 0
        - source: ${target.dir}/etc/grafana
          target: /etc/grafana
          uid: 0
          gid: 0
        - source: ${target.dir}/usr/share/grafana/conf
          target: /usr/share/grafana/conf
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/grafana
          target: /opt/docker/sbom/grafana
          uid: 0
          gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: grafana
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: grafana
      gid: 65532
      members:
        - grafana
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /var/lib/grafana
environment:
  DEBIAN_FRONTEND: noninteractive
  GRAFANA_VERSION: 12.3.2
  PATH: /usr/share/grafana/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin
paths:
  - type: directory
    path: /etc/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/alerting
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/dashboards
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/datasources
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/log/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /tmp
    uid: 65532
    gid: 65532
    mode: "0777"
annotations:
  org.opencontainers.image.description: A minimal Grafana image
  org.opencontainers.image.licenses: AGPL-3.0
entrypoint:
  - grafana
  - server
  - --homepath=/usr/share/grafana
  - --config=/etc/grafana/grafana.ini
  - --packaging=docker
  - cfg:default.log.mode=console
  - cfg:default.paths.data=/var/lib/grafana
  - cfg:default.paths.logs=/var/log/grafana
  - cfg:default.paths.plugins=/var/lib/grafana/plugins
  - cfg:default.paths.provisioning=/etc/grafana/provisioning
ports:
  - 3000/tcp
