# syntax=dhi.io/build:2-helm3

name: kube-vip Helm chart 0.x
image: dhi.io/kube-vip-chart
variant: helm
tags:
  - 0.9.5
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ae9b756a9390301da805f8f72391de2a8c477651
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBE_VIP_REFERENCE: dhi/kube-vip:1.0.4-debian13@sha256:053b1e68b8afda56b5cac72b39ad6c812462a4533a5f9b1aac8ca9fde7672a4c
  SEMVER_MAJOR_MINOR_VERSION: "0.9"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.9.5
  VERSION: 0.9.5
contents:
  builds:
    - name: kube-vip
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/kube-vip/helm-charts.git#kube-vip-0.9.5
            checksum: ae9b756a9390301da805f8f72391de2a8c477651
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-vip
          with:
            chart:
              appRef: kube-vip
              description: Docker Hardened Images Helm chart for kube-vip
              images:
                - name: kube-vip
                  ref: dhi/kube-vip:1.0.4-debian13@sha256:053b1e68b8afda56b5cac72b39ad6c812462a4533a5f9b1aac8ca9fde7672a4c
              name: kube-vip-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kube-vip/helm-charts
            cmd: prepare
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-vip
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-vip
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/kube-vip
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-vip/config
