# syntax=dhi.io/build:2-helm3

name: Clickhouse Operator Helm chart 0.x
image: dhi.io/clickhouse-operator-chart
variant: helm
tags:
  - 0.25.6
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
  CLICKHOUSE_METRICS_EXPORTER_REFERENCE: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:b58f21959507fa4b3ee0fb8e2132b614132d244ab47a7227554ce747f28da4ef
  CLICKHOUSE_OPERATOR_IMAGE_TAG: 0.25.5
  CLICKHOUSE_OPERATOR_REFERENCE: dhi/clickhouse-operator:0.25.6-debian13@sha256:049f96271f0913e9aa6cd1e6b6080c11320a2cddd1687e35f3ec814bf6f3393c
  CLICKHOUSE_SERVER_REFERENCE: dhi/clickhouse-server:25.8.15-debian13@sha256:613f757ec6bd77820151081709de6889d794dcca28e0fa688287d517705b014b
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:6eea9e73a0212e18e3b3863f533836f5f9d9e779e14a28aef5e02aafdcae0c0e
  SEMVER_MAJOR_MINOR_VERSION: "0.25"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.25.6
  VERSION: 0.25.6
contents:
  builds:
    - name: clickhouse-operator-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
      contents:
        files:
          - url: git+https://github.com/Altinity/clickhouse-operator.git#release-0.25.6
            checksum: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            chart:
              appRef: clickhouse-operator
              description: Docker Hardened Images Helm chart for ClickHouse Operator
              images:
                - name: clickhouse-operator
                  ref: dhi/clickhouse-operator:0.25.6-debian13@sha256:049f96271f0913e9aa6cd1e6b6080c11320a2cddd1687e35f3ec814bf6f3393c
                - name: clickhouse-metrics-exporter
                  ref: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:b58f21959507fa4b3ee0fb8e2132b614132d244ab47a7227554ce747f28da4ef
                - name: clickhouse-server
                  ref: dhi/clickhouse-server:25.8.15-debian13@sha256:613f757ec6bd77820151081709de6889d794dcca28e0fa688287d517705b014b
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:6eea9e73a0212e18e3b3863f533836f5f9d9e779e14a28aef5e02aafdcae0c0e
              name: clickhouse-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: clickhouse-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/clickhouse-operator/config
