# syntax=dhi.io/build:2-helm3

name: Clickhouse Operator Helm chart 0.x
image: dhi.io/clickhouse-operator-chart
variant: helm
tags:
  - 0.25.6
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
  CLICKHOUSE_METRICS_EXPORTER_REFERENCE: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:16616b5a3f5697e591f5502f23e29f32ca54a02e368571e7da964a8a48ed720a
  CLICKHOUSE_OPERATOR_IMAGE_TAG: 0.25.5
  CLICKHOUSE_OPERATOR_REFERENCE: dhi/clickhouse-operator:0.25.6-debian13@sha256:830ac54bee31fb988b4fe9697c36334fa9ae85824ca83dacfe8c80fa4069386c
  CLICKHOUSE_SERVER_REFERENCE: dhi/clickhouse-server:25.8.13-debian13@sha256:ed05eb558ba9f48807b37b4471c82e3b9b80463d44143a93c00a1f28ef9a6d40
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:4ee6ac323cf2ac892f44fba7b83ad857dee8022c82ef191b317bd615cd901103
  SEMVER_MAJOR_MINOR_VERSION: "0.25"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.25.6
  VERSION: 0.25.6
contents:
  builds:
    - name: clickhouse-operator-chart
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        files:
          - url: git+https://github.com/Altinity/clickhouse-operator.git#release-0.25.6
            checksum: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            chart:
              appRef: clickhouse-operator
              description: Docker Hardened Images Helm chart for ClickHouse Operator
              images:
                - name: clickhouse-operator
                  ref: dhi/clickhouse-operator:0.25.6-debian13@sha256:830ac54bee31fb988b4fe9697c36334fa9ae85824ca83dacfe8c80fa4069386c
                - name: clickhouse-metrics-exporter
                  ref: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:16616b5a3f5697e591f5502f23e29f32ca54a02e368571e7da964a8a48ed720a
                - name: clickhouse-server
                  ref: dhi/clickhouse-server:25.8.13-debian13@sha256:ed05eb558ba9f48807b37b4471c82e3b9b80463d44143a93c00a1f28ef9a6d40
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:4ee6ac323cf2ac892f44fba7b83ad857dee8022c82ef191b317bd615cd901103
              name: clickhouse-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: clickhouse-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/clickhouse-operator/config
