# syntax=dhi.io/build:1-helm3

name: Clickhouse Operator Helm chart 0.x
image: dhi.io/clickhouse-operator-chart
variant: helm
tags:
  - 0.25.6
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
  CLICKHOUSE_METRICS_EXPORTER_REFERENCE: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:6bb3a07f2eb27cf92a3822f4794f226f1cc986f67bbfc3d40644e66bda93d7c9
  CLICKHOUSE_OPERATOR_IMAGE_TAG: 0.25.5
  CLICKHOUSE_OPERATOR_REFERENCE: dhi/clickhouse-operator:0.25.6-debian13@sha256:d2c02eb857cb4fc4b4585070ff0b1d94413c6931426770f23a8e8478c4a747a7
  CLICKHOUSE_SERVER_REFERENCE: dhi/clickhouse-server:25.8.13-debian13@sha256:ed05eb558ba9f48807b37b4471c82e3b9b80463d44143a93c00a1f28ef9a6d40
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:ac375865ef32495b5bbdc3183396a8fc181d7641f0437b570beabede2d465337
  SEMVER_MAJOR_MINOR_VERSION: "0.25"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.25.6
  VERSION: 0.25.6
contents:
  builds:
    - name: clickhouse-operator-chart
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        files:
          - url: git+https://github.com/Altinity/clickhouse-operator.git#release-0.25.6
            checksum: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            chart:
              appRef: clickhouse-operator
              description: Docker Hardened Images Helm chart for ClickHouse Operator
              images:
                - name: clickhouse-operator
                  ref: dhi/clickhouse-operator:0.25.6-debian13@sha256:d2c02eb857cb4fc4b4585070ff0b1d94413c6931426770f23a8e8478c4a747a7
                - name: clickhouse-metrics-exporter
                  ref: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:6bb3a07f2eb27cf92a3822f4794f226f1cc986f67bbfc3d40644e66bda93d7c9
                - name: clickhouse-server
                  ref: dhi/clickhouse-server:25.8.13-debian13@sha256:ed05eb558ba9f48807b37b4471c82e3b9b80463d44143a93c00a1f28ef9a6d40
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:ac375865ef32495b5bbdc3183396a8fc181d7641f0437b570beabede2d465337
              name: clickhouse-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: clickhouse-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/clickhouse-operator/config
tests:
  - name: Run clickhouse-operator testcontainers helm tests
    directory: chart/clickhouse-operator/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
