# syntax=dhi.io/build:2-helm3

name: Prometheus Blackbox Exporter Helm chart 11.x
image: dhi.io/blackbox-exporter-chart
variant: helm
tags:
  - 11.8.0
platforms:
  - linux/amd64
vars:
  BLACKBOX_EXPORTER_REFERENCE: dhi/blackbox-exporter:0.28.0-debian13@sha256:674ebb808883cdd2aeda9c5a5323baeb9fdda875871be033f6f350cf7a3c0e93
  CHART_COMMIT_SHA: c55ebb0fd735c43a657954b0dcabc101281ed373
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2ed3c5e3d910d1f1e38eb00618e7c9a3c08e7cb11b8d6b127477a223f1c0a1b5
  SEMVER_MAJOR_MINOR_VERSION: "11.8"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.8.0
  VERSION: 11.8.0
contents:
  builds:
    - name: blackbox-exporter-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-blackbox-exporter-11.8.0
            checksum: c55ebb0fd735c43a657954b0dcabc101281ed373
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            chart:
              appRef: blackbox-exporter
              description: Docker Hardened Images Helm chart for Prometheus Blackbox Exporter
              images:
                - name: blackbox-exporter
                  ref: dhi/blackbox-exporter:0.28.0-debian13@sha256:674ebb808883cdd2aeda9c5a5323baeb9fdda875871be033f6f350cf7a3c0e93
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2ed3c5e3d910d1f1e38eb00618e7c9a3c08e7cb11b8d6b127477a223f1c0a1b5
              name: blackbox-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-blackbox-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/blackbox-exporter/config
