# syntax=dhi.io/build:2-helm3

name: HAProxy Helm chart 1.x
image: dhi.io/haproxy-chart
variant: helm
tags:
  - 1.28.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 982c4adb3c203399ba017c10d7bdf4bd434b0a58
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HAPROXY_REFERENCE: dhi/haproxy:3.1.12-debian13@sha256:6b96ca7d5904cfb05a569048a5124d6fc4b42273e241d8fe20816a6d2bc8a897
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:a9247b60e56f190fb6de43042004c80b6ad903fe8df5becc513d89066aa3221c
  SEMVER_MAJOR_MINOR_VERSION: "1.28"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.28.0
  VERSION: 1.28.0
contents:
  builds:
    - name: haproxy
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:a9247b60e56f190fb6de43042004c80b6ad903fe8df5becc513d89066aa3221c
      contents:
        files:
          - url: git+https://github.com/haproxytech/helm-charts.git#haproxy-1.28.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/haproxy
          with:
            chart:
              appRef: haproxy
              description: Docker Hardened Images Helm chart for HAProxy
              images:
                - name: haproxy
                  ref: dhi/haproxy:3.1.12-debian13@sha256:6b96ca7d5904cfb05a569048a5124d6fc4b42273e241d8fe20816a6d2bc8a897
              name: haproxy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/haproxytech/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/haproxy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/haproxy
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: haproxy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/haproxy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/haproxy/config
