# syntax=dhi.io/build:1-helm3

name: Fluent Bit Helm chart 0.x
image: dhi.io/fluent-bit-chart
variant: helm
tags:
  - 0.54.0
platforms:
  - linux/amd64
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
  CHART_COMMIT_SHA: 8749b0a79f6837523dc461a34a7c9ad286ee6857
  CONFIGMAP_RELOAD_REFERENCE: dhi/configmap-reload:0.15.0-debian13@sha256:7abb3e521c026504443320b4e2a4e427d5835c830f6ba85206eaa069c3dad4c7
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FLUENT_BIT_REFERENCE: dhi/fluent-bit:4.2.2-debian13@sha256:6bd1be66eb4e2328caf843d9f3e046946ea8b87811c2764e2512f6d514e1dea5
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  SEMVER_MAJOR_MINOR_VERSION: "0.54"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.54.0
  VERSION: 0.54.0
contents:
  builds:
    - name: fluent-bit
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/fluent/helm-charts.git#fluent-bit-0.54.0
            checksum: 8749b0a79f6837523dc461a34a7c9ad286ee6857
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/fluent-bit
          with:
            chart:
              appRef: fluent-bit
              description: Docker Hardened Images Helm chart for Fluent Bit
              images:
                - name: fluent-bit
                  ref: dhi/fluent-bit:4.2.2-debian13@sha256:6bd1be66eb4e2328caf843d9f3e046946ea8b87811c2764e2512f6d514e1dea5
                - name: configmap-reload
                  ref: dhi/configmap-reload:0.15.0-debian13@sha256:7abb3e521c026504443320b4e2a4e427d5835c830f6ba85206eaa069c3dad4c7
                - name: busybox
                  ref: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
              name: fluent-bit-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/fluent/fluent-bit
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/fluent-bit
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: fluent-bit
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: fluent-bit
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fluent-bit/config
tests:
  - name: Run fluent-bit testcontainers helm tests
    directory: chart/fluent-bit/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
