# syntax=dhi.io/build:2-helm3

name: Fluent Bit Helm chart 0.x
image: dhi.io/fluent-bit-chart
variant: helm
tags:
  - 0.55.0
platforms:
  - linux/amd64
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
  CHART_COMMIT_SHA: a359bcb5bcc16126b528a10afef8bd26eebd19a8
  CONFIGMAP_RELOAD_REFERENCE: dhi/configmap-reload:0.15.0-debian13@sha256:cb60ab48307f6a806574d89520b9f8a2766a37a9940632b7672872915b7b5a51
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FLUENT_BIT_REFERENCE: dhi/fluent-bit:4.2.2-debian13@sha256:7edf13a45aa3e523c51372b9dfa28950f69644acc364f88e9995fc6ceb0b85a7
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
  SEMVER_MAJOR_MINOR_VERSION: "0.55"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.55.0
  VERSION: 0.55.0
contents:
  builds:
    - name: fluent-bit
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/fluent/helm-charts.git#fluent-bit-0.55.0
            checksum: a359bcb5bcc16126b528a10afef8bd26eebd19a8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/fluent-bit
          with:
            chart:
              appRef: fluent-bit
              description: Docker Hardened Images Helm chart for Fluent Bit
              images:
                - name: fluent-bit
                  ref: dhi/fluent-bit:4.2.2-debian13@sha256:7edf13a45aa3e523c51372b9dfa28950f69644acc364f88e9995fc6ceb0b85a7
                - name: configmap-reload
                  ref: dhi/configmap-reload:0.15.0-debian13@sha256:cb60ab48307f6a806574d89520b9f8a2766a37a9940632b7672872915b7b5a51
                - name: busybox
                  ref: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
              name: fluent-bit-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/fluent/fluent-bit
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/fluent-bit
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: fluent-bit
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: fluent-bit
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fluent-bit/config
