metadata:
  display-name: Fairwinds VPA Helm chart
  short-description: Helm chart to install Kubernetes Vertical Pod Autoscaler that suits Fairwinds suit of products.
  featured: false
  home-url: https://github.com/FairwindsOps/charts/tree/master/stable/vpa
  categories:
    - monitoring-and-observability
