# syntax=dhi.io/build:1-helm3

name: External Secrets Operator Helm chart 0.x
image: dhi.io/external-secrets-chart
variant: helm
tags:
  - 0.20.4
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: e594d361184afb8bd76f246490fff2d74c9a4849
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  EXTERNAL_SECRETS_REFERENCE: dhi/external-secrets:0.20.4-debian13@sha256:654a466bba5e5f65aa8bdfe7f3b5857aba08036d6cd4945a199bd91bba53cd74
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  SEMVER_MAJOR_MINOR_VERSION: "0.20"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.20.4
  VERSION: 0.20.4
contents:
  builds:
    - name: external-secrets
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/external-secrets/external-secrets.git#helm-chart-0.20.4
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/external-secrets
          with:
            chart:
              appRef: external-secrets
              description: Docker Hardened Images Helm chart for External Secrets Operator
              images:
                - name: external-secrets
                  ref: dhi/external-secrets:0.20.4-debian13@sha256:654a466bba5e5f65aa8bdfe7f3b5857aba08036d6cd4945a199bd91bba53cd74
              name: external-secrets-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/external-secrets/external-secrets
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/external-secrets
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/deploy/charts/external-secrets
          runs: |
            set -eux -o pipefail

            yq eval 'del(.dependencies)' Chart.yaml \
              | awk '{print} END{print ""}' > tmp && mv tmp Chart.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/charts/external-secrets
            cmd: dependency update
        - name: generate CRDs
          runs: |
            set -eux -o pipefail

            cd ${source.dir}/helm-charts

            make helm.generate
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: external-secrets
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/charts/external-secrets
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/external-secrets/config
tests:
  - name: Run external-secrets testcontainers helm tests
    directory: chart/external-secrets/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
