# syntax=dhi.io/build:2-helm3

name: Kyverno Policy Reporter Helm chart 3.x
image: dhi.io/kyverno-policy-reporter-chart
variant: helm
tags:
  - 3.7.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 9019bd04f5424605945478095df8a858f409ce5b
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
  POLICY_REPORTER_IMAGE_TAG: 3.7.0
  POLICY_REPORTER_REFERENCE: dhi/kyverno-policy-reporter:3.7.0-debian13@sha256:a28b72ef0c73cc1c89fe9f410ad6ee27cc746d4a8238be0fbb8dc48694c608c9
  POLICY_REPORTER_UI_IMAGE_TAG: 2.5.1
  POLICY_REPORTER_UI_REFERENCE: dhi/kyverno-policy-reporter-ui:2.5.1-debian13@sha256:eb8a416ff93d674096588b7340a23446a5353dfdfdbeba6cc05f6539cbccc6b2
  SEMVER_MAJOR_MINOR_VERSION: "3.7"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.7.1
  TRIVY_IMAGE_TAG: 0.69.0
  TRIVY_REFERENCE: dhi/trivy:0.69.0-debian13@sha256:1d51a7ae377c16d7d8b3b1c47c2844ddc006b993faf3663ce8b361872839889e
  VERSION: 3.7.1
contents:
  builds:
    - name: kyverno-policy-reporter
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/kyverno/policy-reporter.git#policy-reporter-3.7.1
            checksum: 9019bd04f5424605945478095df8a858f409ce5b
            path: ${source.dir}/policy-reporter
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/policy-reporter/charts/policy-reporter
          with:
            chart:
              appRef: kyverno-policy-reporter
              description: Docker Hardened Images Helm chart for Kyverno Policy Reporter
              images:
                - name: kyverno-policy-reporter
                  ref: dhi/kyverno-policy-reporter:3.7.0-debian13@sha256:a28b72ef0c73cc1c89fe9f410ad6ee27cc746d4a8238be0fbb8dc48694c608c9
                - name: kyverno-policy-reporter-ui
                  ref: dhi/kyverno-policy-reporter-ui:2.5.1-debian13@sha256:eb8a416ff93d674096588b7340a23446a5353dfdfdbeba6cc05f6539cbccc6b2
                - name: trivy
                  ref: dhi/trivy:0.69.0-debian13@sha256:1d51a7ae377c16d7d8b3b1c47c2844ddc006b993faf3663ce8b361872839889e
              name: kyverno-policy-reporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/policy-reporter
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/policy-reporter/charts/policy-reporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: blank 3rd party plugin images
          work-dir: ${source.dir}/policy-reporter/charts/policy-reporter
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party image for kyverno-plugin by matching the specific values path
            sed -i 's|^\([[:space:]]*\)image: "{{ .Values.plugin.kyverno.image.registry }}/{{ .Values.plugin.kyverno.image.repository }}:{{ .Values.plugin.kyverno.image.tag }}"|\1image: "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED|' ./templates/plugins/kyverno/deployment.yaml

            # Blank out the 3rd party image for trivy-plugin (NOT the trivy CLI which uses plugin.trivy.cli.image)
            sed -i 's|^\([[:space:]]*\)image: "{{ .Values.plugin.trivy.image.registry }}/{{ .Values.plugin.trivy.image.repository }}:{{ .Values.plugin.trivy.image.tag }}"|\1image: "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED|' ./templates/plugins/trivy/deployment.yaml
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/policy-reporter/charts
          with:
            chart: policy-reporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/policy-reporter/charts/policy-reporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno-policy-reporter/config
