recommender:
  image:
    repository: ${vpa-recommender.registry}/${vpa-recommender.repository}
    tag: ${vpa-recommender.tag}@${vpa-recommender.digest}
  podSecurityContext:
    fsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
updater:
  image:
    repository: ${vpa-updater.registry}/${vpa-updater.repository}
    tag: ${vpa-updater.tag}@${vpa-updater.digest}
  podSecurityContext:
    fsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
admissionController:
  image:
    repository: ${vpa-admission-controller.registry}/${vpa-admission-controller.repository}
    tag: ${vpa-admission-controller.tag}@${vpa-admission-controller.digest}
  podSecurityContext:
    fsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
  certGen:
    image:
      repository: ${kube-webhook-certgen.registry}/${kube-webhook-certgen.repository}
      tag: ${kube-webhook-certgen.tag}@${kube-webhook-certgen.digest}
    podSecurityContext:
      fsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532

tests:
  image:
    repository: ${kubectl.registry}/${kubectl.repository}
    tag: ${kubectl.tag}@${kubectl.digest}

# Upstream already sets run as non-root on all containers
