# syntax=dhi.io/build:2-helm3

name: Thanos Helm chart 0.x
image: dhi.io/thanos-chart
variant: helm
tags:
  - 0.39.2
platforms:
  - linux/amd64
vars:
  BASH_REFERENCE: dhi/bash:5.2.37-debian13@sha256:08916a31cadcc5560f7429cb78aedcc9287977a74401bbf80dcb52f0fae8a4aa
  CHART_COMMIT_SHA: cd04b0e93380dcb987c52a214b20cd6864362d9d
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  SEMVER_MAJOR_MINOR_VERSION: "0.39"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.39.2
  THANOS_REFERENCE: dhi/thanos:0.41.0-debian13@sha256:248d3e6cd93dfac46631567bdc4e308e8a36212e34adf52bea5e4230557e1725
  VERSION: 0.39.2
contents:
  builds:
    - name: thanos
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#thanos/0.39.2
            checksum: cd04b0e93380dcb987c52a214b20cd6864362d9d
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/thanos
          with:
            chart:
              appRef: thanos
              description: Docker Hardened Images Helm chart for Thanos
              images:
                - name: thanos
                  ref: dhi/thanos:0.41.0-debian13@sha256:248d3e6cd93dfac46631567bdc4e308e8a36212e34adf52bea5e4230557e1725
                - name: bash
                  ref: dhi/bash:5.2.37-debian13@sha256:08916a31cadcc5560f7429cb78aedcc9287977a74401bbf80dcb52f0fae8a4aa
              name: thanos-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/thanos
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/thanos
          with:
            file: values.yaml
            patches:
              - del(.minio)
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/thanos
          with:
            file: Chart.yaml
            patches:
              - del(.dependencies.0)
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/thanos
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: thanos
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: thanos
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/thanos/config
