# syntax=dhi.io/build:2-helm3

name: Istio ZTunnel Helm chart 1.x
image: dhi.io/ztunnel-chart
variant: helm
tags:
  - 1.27.5
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 4e291059a25d05161759d4d848308dd25251b3fe
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
  SEMVER_MAJOR_MINOR_VERSION: "1.27"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.27.5
  VERSION: 1.27.5
  ZTUNNEL_REFERENCE: dhi/ztunnel:1.27.5-debian13@sha256:49550a51805317aae45f5ce41a95abf4e9eb31d9cf35649ed8ff5d23da330a41
contents:
  builds:
    - name: ztunnel
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.27.5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            chart:
              appRef: ztunnel
              description: Docker Hardened Images Helm chart for ZTunnel
              images:
                - name: ztunnel
                  ref: dhi/ztunnel:1.27.5-debian13@sha256:49550a51805317aae45f5ce41a95abf4e9eb31d9cf35649ed8ff5d23da330a41
              name: ztunnel-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: ztunnel
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/ztunnel/config
