# syntax=dhi.io/build:1-helm3

name: Istio ZTunnel Helm chart 1.x
image: dhi.io/ztunnel-chart
variant: helm
tags:
  - 1.27.5
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 4e291059a25d05161759d4d848308dd25251b3fe
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  SEMVER_MAJOR_MINOR_VERSION: "1.27"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.27.5
  VERSION: 1.27.5
  ZTUNNEL_REFERENCE: dhi/ztunnel:1.27.5-debian13@sha256:a4ec17b19e418f9f7d8a9dcb689d8eb3073c0eb120ccc0124314b2795010799e
contents:
  builds:
    - name: ztunnel
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.27.5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            chart:
              appRef: ztunnel
              description: Docker Hardened Images Helm chart for ZTunnel
              images:
                - name: ztunnel
                  ref: dhi/ztunnel:1.27.5-debian13@sha256:a4ec17b19e418f9f7d8a9dcb689d8eb3073c0eb120ccc0124314b2795010799e
              name: ztunnel-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: ztunnel
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/ztunnel/config
tests:
  - name: Run ztunnel testcontainers helm tests
    directory: chart/ztunnel/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
