# syntax=dhi.io/build:2-helm3

name: Dex Helm chart 0.x
image: dhi.io/dex-chart
variant: helm
tags:
  - 0.24.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: c82afcc25e9d6a807111ba637b1a4568f9033fc6
  DEX_IMAGE_TAG: 2.44.0
  DEX_REFERENCE: dhi/dex:2.44.0-debian13@sha256:c621d4f2f0b76edf5d9877fdcd95a7cc7ea9f9555345c1766859bf3a3640fdde
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
  SEMVER_MAJOR_MINOR_VERSION: "0.24"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.24.0
  VERSION: 0.24.0
contents:
  builds:
    - name: dex
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/dexidp/helm-charts.git#dex-0.24.0
            checksum: c82afcc25e9d6a807111ba637b1a4568f9033fc6
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/dex
          with:
            chart:
              appVersion: 2.44.0
              description: Docker Hardened Images Helm chart for Dex
              images:
                - name: dex
                  ref: dhi/dex:2.44.0-debian13@sha256:c621d4f2f0b76edf5d9877fdcd95a7cc7ea9f9555345c1766859bf3a3640fdde
              name: dex-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/dexidp/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/dex
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/dex
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: dex
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/dex
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/dex/config
