# syntax=dhi.io/build:2-helm3

name: Promtail Helm chart 6.x
image: dhi.io/promtail-chart
variant: helm
tags:
  - 6.17.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b68e01680c1aa5230134a6620ac5c9c6ac007985
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.88.1-debian13@sha256:e56fef5adce639d753100c9f865bd4bf914b67185a65ba83c930ee444d9b35d9
  PROMTAIL_REFERENCE: dhi/promtail:3.5.9-debian13@sha256:28c49c44c33f3b62ae7fda65232f17dc0ef34f971cc362cabce231ca5bd84f91
  SEMVER_MAJOR_MINOR_VERSION: "6.17"
  SEMVER_MAJOR_VERSION: "6"
  SEMVER_VERSION: 6.17.1
  VERSION: 6.17.1
contents:
  builds:
    - name: promtail
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana/helm-charts.git#promtail-6.17.1
            checksum: b68e01680c1aa5230134a6620ac5c9c6ac007985
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/promtail
          with:
            chart:
              appRef: promtail
              description: Docker Hardened Images Helm chart for Promtail
              images:
                - name: promtail
                  ref: dhi/promtail:3.5.9-debian13@sha256:28c49c44c33f3b62ae7fda65232f17dc0ef34f971cc362cabce231ca5bd84f91
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.88.1-debian13@sha256:e56fef5adce639d753100c9f865bd4bf914b67185a65ba83c930ee444d9b35d9
              name: promtail-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: remove default volumes
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            file: promtail/values.yaml
            patches:
              - del(.defaultVolumes)
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/promtail
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: promtail
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: promtail
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/promtail/config
