image:
  repository: ${fluent-bit.registry}/${fluent-bit.repository}
  tag: ${fluent-bit.tag}
  digest: ${fluent-bit.digest}

command:
  - /usr/local/bin/fluent-bit # https://docker.atlassian.net/browse/DHI-1730

testFramework:
  image:
    repository: ${busybox.registry}/${busybox.repository}
    tag: ${busybox.tag}
    digest: ${busybox.digest}

hotReload:
  image:
    repository: ${configmap-reload.registry}/${configmap-reload.repository}
    tag: ${configmap-reload.tag}
    digest: ${configmap-reload.digest}

podSecurityContext:
  fsGroup: 65532
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
