# syntax=dhi.io/build:2-helm3

name: Goldilocks Helm chart 10.x
image: dhi.io/goldilocks-chart
variant: helm
tags:
  - 10.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 21ba576f9bfc18ef6debcf4a7fe2543276fa5fed
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FAIRWINDS_VPA_REFERENCE: dhi/fairwinds-vpa-chart:4.10.1@sha256:1091073fa0db7d91f0863626f69d2239705ba59e4f5d43b2a4f8bad5bfc80c1e
  GOLDILOCKS_REFERENCE: dhi/goldilocks:4.14.9-debian13@sha256:f08817dc0a1dabc44ca933dec7cbb4a509192b134132b6784876574e4ed74ecb
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  METRICS_SERVER_REFERENCE: dhi/metrics-server-chart:3.13.0@sha256:0e43583d726ced38c57231657bf312947c904bf514217e1526a329ccc90dc031
  SEMVER_MAJOR_MINOR_VERSION: "10.2"
  SEMVER_MAJOR_VERSION: "10"
  SEMVER_VERSION: 10.2.0
  VERSION: 10.2.0
contents:
  builds:
    - name: goldilocks-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#21ba576f9bfc18ef6debcf4a7fe2543276fa5fed
            checksum: 21ba576f9bfc18ef6debcf4a7fe2543276fa5fed
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/goldilocks
          with:
            chart:
              appRef: goldilocks
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.0@sha256:0e43583d726ced38c57231657bf312947c904bf514217e1526a329ccc90dc031
                - alias: vpa
                  condition: vpa.enabled
                  name: vpa
                  ref: dhi/fairwinds-vpa-chart:4.10.1@sha256:1091073fa0db7d91f0863626f69d2239705ba59e4f5d43b2a4f8bad5bfc80c1e
              description: Docker Hardened Images Helm chart for Goldilocks
              images:
                - name: goldilocks
                  ref: dhi/goldilocks:4.14.9-debian13@sha256:f08817dc0a1dabc44ca933dec7cbb4a509192b134132b6784876574e4ed74ecb
              name: goldilocks-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/goldilocks
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: goldilocks
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: goldilocks
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: goldilocks
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/goldilocks/config
