# syntax=dhi.io/build:1-debian13

name: Prometheus Config Reloader 0.x
image: dhi.io/prometheus-config-reloader
variant: runtime
tags:
  - "0"
  - "0.87"
  - 0.87.1
  - 0-debian13
  - 0.87-debian13
  - 0.87.1-debian13
platforms:
  - linux/amd64
  - linux/arm64
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: a50aee4108dcf07f86b1b3e9dfa2bd6ee167f8a8
  GO_REFERENCE: dhi/golang:1.25.5-debian13-dev@sha256:8c2284d70af13cb934da5f05f5fa58a776aa963e88ebf542970ba09f4e3a0bbf
  GO_VERSION: 1.25.5
  SEMVER_MAJOR_MINOR_VERSION: "0.87"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.87.1
  TAG: v0.87.1
  VERSION: 0.87.1
contents:
  packages:
    - '!base-files'
  builds:
    - name: prometheus-config-reloader
      uses: dhi.io/golang:1.25.5-debian13-dev@sha256:8c2284d70af13cb934da5f05f5fa58a776aa963e88ebf542970ba09f4e3a0bbf
      contents:
        files:
          - url: git+https://github.com/prometheus-operator/prometheus-operator.git#v0.87.1
            checksum: a50aee4108dcf07f86b1b3e9dfa2bd6ee167f8a8
            path: /go/src/github.com/prometheus-operator/prometheus-operator
            spdx:
              name: prometheus-operator
              version: 0.87.1
              packages:
                - name: prometheus-operator
                  purl: pkg:golang/github.com/prometheus-operator/prometheus-operator@0.87.1
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/prometheus-operator/prometheus-operator
          with:
            deps:
              - golang.org/x/crypto@v0.45.0
            download: true
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/prometheus-operator/prometheus-operator
          with:
            ldflags:
              - -X github.com/prometheus/common/version.Version=0.87.1
              - -X github.com/prometheus/common/version.Revision=a50aee4108dcf07f86b1b3e9dfa2bd6ee167f8a8
              - -X github.com/prometheus/common/version.Branch=dhi
              - -X github.com/prometheus/common/version.BuildUser=dhi
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/local/bin/prometheus-config-reloader
            packages: ./cmd/prometheus-config-reloader/
      outputs:
        - source: ${target.dir}/usr/local/bin
          target: /usr/local/bin
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/prometheus-operator
          target: /opt/docker/sbom/prometheus-operator
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
paths:
  - type: symlink
    path: /usr/bin/prometheus-config-reloader
    uid: 0
    gid: 0
    source: /usr/local/bin/prometheus-config-reloader
annotations:
  org.opencontainers.image.description: A minimal prometheus-config-reloader image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/local/bin/prometheus-config-reloader
tests:
  - name: Run prometheus-config-reloader testcontainers tests
    directory: image/prometheus-config-reloader/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run testcontainers basic tests
    directory: test/go-testing/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
