# syntax=dhi.io/build:1-debian13

name: Helm 4.x (dev)
image: dhi.io/helm
variant: dev
tags:
  - 4-dev
  - 4.0-dev
  - 4.0.4-dev
  - 4-debian13-dev
  - 4.0-debian13-dev
  - 4.0.4-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: 8650e1dad9e6ae38b41f60b712af9218a0d8cc11
  GO_DIGEST: sha256:a45faad20adc1286eef26b1f30e170b54791c217ce69457784de66b0a13d1fe6
  GO_VERSION: 1.25.5
  SEMVER_MAJOR_MINOR_VERSION: "4.0"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.0.4
  VERSION: 4.0.4
  YQ_REFERENCE: dhi/pkg-go-yq:4.49.2-debian13@sha256:1364e03f4fa31c3eb6c741262ada6709691dccea3e1f6e32fabf1f711539e639
  YQ_VERSION: 4.49.2
contents:
  packages:
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - base-files
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - util-linux
  builds:
    - name: helm
      uses: dhi.io/golang:1.25.5-debian13-dev@sha256:a45faad20adc1286eef26b1f30e170b54791c217ce69457784de66b0a13d1fe6
      contents:
        packages:
          - sed
        files:
          - url: git+https://github.com/helm/helm.git#v4.0.4
            checksum: 8650e1dad9e6ae38b41f60b712af9218a0d8cc11
            path: /go/src/github.com/helm/helm
            spdx:
              name: helm
              version: 4.0.4
              packages:
                - name: helm
                  purl: pkg:golang/helm.sh/helm/v3@4.0.4
                  license: Apache-2.0
            uid: 65532
            gid: 65532
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/helm/helm
          with:
            deps:
              - golang.org/x/crypto@v0.45.0
            download: true
        - name: build
          work-dir: /go/src/github.com/helm/helm
          runs: |
            set -eux -o pipefail

            GOLDFLAGS="-X helm.sh/helm/v4/internal/version.version=4.0.4
                       -X helm.sh/helm/v4/internal/version.gitCommit=8650e1dad9e6ae38b41f60b712af9218a0d8cc11
                       -X helm.sh/helm/v4/internal/version.gitTreeState=clean
                       -X helm.sh/helm/v4/internal/version.metadata="

            mkdir -p "${target.dir}/usr/local/bin"
            CGO_ENABLED=0 go build \
              -ldflags="$GOLDFLAGS" \
              -o "${target.dir}/usr/local/bin/helm" ./cmd/helm
      accounts:
        run-as: nonroot
        users:
          - name: nonroot
            uid: 65532
            gid: 65532
        groups:
          - name: nonroot
            gid: 65532
            members:
              - nonroot
      outputs:
        - source: ${target.dir}/usr/local/bin
          target: /usr/local/bin
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/helm
          target: /opt/docker/sbom/helm
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/pkg-go-yq:4.49.2-debian13@sha256:1364e03f4fa31c3eb6c741262ada6709691dccea3e1f6e32fabf1f711539e639
      includes:
        - opt/docker/sbom/yq
        - usr/local/bin/yq
      uid: 0
      gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /workspace
environment:
  DEBIAN_FRONTEND: noninteractive
paths:
  - type: directory
    path: /workspace
    uid: 65532
    gid: 65532
    mode: "0755"
annotations:
  org.opencontainers.image.description: A minimal Helm image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - helm
cmd:
  - help
tests:
  - name: Run testcontainers tests
    directory: image/helm/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run testcontainers basic tests
    directory: test/go-testing/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run APT package manager tests
    directory: test/go-testing/package_manager
    commands:
      - go test . -count=1 -v
    exit-code: 0
