# syntax=dhi.io/build:2-helm3

name: Argo CD Image Updater Helm chart 1.x
image: dhi.io/argocd-image-updater-chart
variant: helm
tags:
  - 1.1.1
platforms:
  - linux/amd64
vars:
  ARGOCD_IMAGE_UPDATER_REFERENCE: dhi/argocd-image-updater:1.1.0-debian13@sha256:f6c3a3b5950080986a9c1ed4bb527b030941e12f5a6a3f417910eea33f8b810f
  CHART_COMMIT_SHA: 252c60636da95a03ce357425aa4d562eb5762641
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
  SEMVER_MAJOR_MINOR_VERSION: "1.1"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.1.1
  VERSION: 1.1.1
contents:
  builds:
    - name: argocd-image-updater
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/argoproj/argo-helm#argocd-image-updater-1.1.1
            checksum: 252c60636da95a03ce357425aa4d562eb5762641
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/argocd-image-updater
          with:
            chart:
              appRef: argocd-image-updater
              description: Docker Hardened Images Helm chart for Argo CD Image Updater
              images:
                - name: argocd-image-updater
                  ref: dhi/argocd-image-updater:1.1.0-debian13@sha256:f6c3a3b5950080986a9c1ed4bb527b030941e12f5a6a3f417910eea33f8b810f
              name: argocd-image-updater-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/argoproj/argo-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/argocd-image-updater
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: argocd-image-updater
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: argocd-image-updater
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: argocd-image-updater
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/argocd-image-updater/config
