# syntax=dhi.io/build:2-helm3

name: OpenSearch Helm chart 3.x
image: dhi.io/opensearch-chart
variant: helm
tags:
  - 3.4.0
platforms:
  - linux/amd64
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
  CHART_COMMIT_SHA: faa0693a5f5ff85b2804bc5934a6bea19709ef6d
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
  OPENSEARCH_REFERENCE: dhi/opensearch:3.4.0-debian13@sha256:09d714c9a3783617e7459c5aa9509c6ee056a54daaf717e6470c17f767b66f13
  SEMVER_MAJOR_MINOR_VERSION: "3.4"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.4.0
  VERSION: 3.4.0
contents:
  builds:
    - name: opensearch
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
      contents:
        files:
          - url: git+https://github.com/opensearch-project/helm-charts.git#opensearch-3.4.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opensearch
          with:
            chart:
              appRef: opensearch
              description: Docker Hardened Images Helm chart for OpenSearch
              images:
                - name: opensearch
                  ref: dhi/opensearch:3.4.0-debian13@sha256:09d714c9a3783617e7459c5aa9509c6ee056a54daaf717e6470c17f767b66f13
                - name: busybox
                  ref: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
              name: opensearch-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/opensearch-project/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opensearch
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/opensearch
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opensearch
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/opensearch
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opensearch/config
