# syntax=dhi.io/build:1-helm3

name: Grafana Alloy Helm chart 1.x
image: dhi.io/alloy-chart
variant: helm
tags:
  - 1.5.1
platforms:
  - linux/amd64
vars:
  ALLOY_IMAGE_TAG: 1.12.0
  ALLOY_REFERENCE: dhi/alloy:1.12.1-debian13@sha256:75f2a952d545c8e75459c80afcffc3885b9c810f04ae31b1fba5c9fecdf07f58
  CHART_COMMIT_SHA: a1861605c3744006d26caecc380a2fdc2845757a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.87.1-debian13@sha256:f960fb3a029a5ce137bc6e8462d053a78ab0c2b5c437560b35bc5f5d62095255
  SEMVER_MAJOR_MINOR_VERSION: "1.5"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.5.1
  VERSION: 1.5.1
contents:
  builds:
    - name: alloy
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana/alloy.git#helm-chart/1.5.1
            checksum: a1861605c3744006d26caecc380a2fdc2845757a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            chart:
              appRef: alloy
              dependencies:
                - keep: true
                  name: crds
              description: Docker Hardened Images Helm chart for Grafana Alloy
              images:
                - name: alloy
                  ref: dhi/alloy:1.12.1-debian13@sha256:75f2a952d545c8e75459c80afcffc3885b9c810f04ae31b1fba5c9fecdf07f58
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.87.1-debian13@sha256:f960fb3a029a5ce137bc6e8462d053a78ab0c2b5c437560b35bc5f5d62095255
              name: alloy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/alloy
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alloy/config
tests:
  - name: Run alloy testcontainers helm tests
    directory: chart/alloy/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
