# syntax=dhi.io/build:2-helm3

name: Grafana Alloy Helm chart 1.x
image: dhi.io/alloy-chart
variant: helm
tags:
  - 1.6.0
platforms:
  - linux/amd64
vars:
  ALLOY_IMAGE_TAG: 1.12.0
  ALLOY_REFERENCE: dhi/alloy:1.13.0-debian13@sha256:c1438cab1ae072c6e691e8af520f1e53df2be5ca452b403b4cfe18bb7e70251e
  CHART_COMMIT_SHA: 44ddc6937c2a734e603616d9bf22858a82049bfb
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2ed3c5e3d910d1f1e38eb00618e7c9a3c08e7cb11b8d6b127477a223f1c0a1b5
  SEMVER_MAJOR_MINOR_VERSION: "1.6"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.6.0
  VERSION: 1.6.0
contents:
  builds:
    - name: alloy
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana/alloy.git#helm-chart/1.6.0
            checksum: 44ddc6937c2a734e603616d9bf22858a82049bfb
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            chart:
              appRef: alloy
              dependencies:
                - keep: true
                  name: crds
              description: Docker Hardened Images Helm chart for Grafana Alloy
              images:
                - name: alloy
                  ref: dhi/alloy:1.13.0-debian13@sha256:c1438cab1ae072c6e691e8af520f1e53df2be5ca452b403b4cfe18bb7e70251e
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2ed3c5e3d910d1f1e38eb00618e7c9a3c08e7cb11b8d6b127477a223f1c0a1b5
              name: alloy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/alloy
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alloy/config
