operator:
  image:
    repository: ${clickhouse-operator.registry}/${clickhouse-operator.repository}
    tag: ${clickhouse-operator.tag}@${clickhouse-operator.digest}
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

metrics:
  image:
    repository: ${clickhouse-metrics-exporter.registry}/${clickhouse-metrics-exporter.repository}
    tag: ${clickhouse-metrics-exporter.tag}@${clickhouse-metrics-exporter.digest}
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

crdHook:
  image:
    repository: ${kubectl.registry}/${kubectl.repository}
    tag: ${kubectl.tag}@${kubectl.digest}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
