# syntax=dhi.io/build:2-helm3

name: Traefik Helm chart 37.x
image: dhi.io/traefik-chart
variant: helm
tags:
  - 37.4.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 75bdb79d11e23560eebb0302f030121e5cfb081f
  COMMIT_SHA: 64d25f2c7dd932b3b7dc27d0bfa6ea131fc280f3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
  SEMVER_MAJOR_MINOR_VERSION: "37.4"
  SEMVER_MAJOR_VERSION: "37"
  SEMVER_VERSION: 37.4.0
  TRAEFIK_REFERENCE: dhi/traefik:3.6.7-debian13@sha256:8493b1176d140b84e7c26112498248d574680a028eec7dca570c3c9b5e885faf
  TRAEFIK_VERSION: 3.6.5
  VERSION: 37.4.0
contents:
  builds:
    - name: traefik
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
      contents:
        files:
          - url: git+https://github.com/traefik/traefik-helm-chart.git#v37.4.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/traefik
          with:
            chart:
              appRef: traefik
              description: Docker Hardened Images Helm chart for Traefik
              images:
                - name: traefik
                  ref: dhi/traefik:3.6.7-debian13@sha256:8493b1176d140b84e7c26112498248d574680a028eec7dca570c3c9b5e885faf
              name: traefik-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/traefik/traefik-helm-chart
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/traefik
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/traefik
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: traefik
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/traefik
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/traefik/config
