# syntax=dhi.io/build:1-helm3

name: Prometheus AlertManager Helm chart 1.x
image: dhi.io/alertmanager-chart
variant: helm
tags:
  - 1.9.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_IMAGE_REFERENCE: dhi/alertmanager:0.30.0-debian13@sha256:ab64a18294e008fcafedb8fe0d7cc278a5c9f9042f2dd5dd3c52ae262aef0bc4
  BUSYBOX_IMAGE_REFERENCE: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
  CHART_COMMIT_SHA: fcac966ef229709039b1610ee19afcf17104f082
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.87.1-debian13@sha256:181186c36a4a0974653cab58f03c2f35e113aeecaacc44b9fb6d7fe45ff5d927
  SEMVER_MAJOR_MINOR_VERSION: "1.9"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.9.0
  VERSION: 1.9.0
contents:
  builds:
    - name: alertmanager
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#alertmanager-1.9.0
            checksum: fcac966ef229709039b1610ee19afcf17104f082
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/alertmanager/
          with:
            chart:
              appRef: alertmanager
              description: Docker Hardened Images Helm chart for Prometheus AlertManager
              images:
                - name: alertmanager
                  ref: dhi/alertmanager:0.30.0-debian13@sha256:ab64a18294e008fcafedb8fe0d7cc278a5c9f9042f2dd5dd3c52ae262aef0bc4
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.87.1-debian13@sha256:181186c36a4a0974653cab58f03c2f35e113aeecaacc44b9fb6d7fe45ff5d927
                - name: busybox
                  ref: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
              name: alertmanager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/alertmanager/
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: relocate test-connection template
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/alertmanager
          with:
            chart:
              mappings:
                - file: templates/tests/test-connection.yaml
                  raw: 'image: busybox'
                  replaceWith: 'image: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2'
            cmd: relocate
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/alertmanager
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: alertmanager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/alertmanager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alertmanager/config
tests:
  - name: Run alertmanager testcontainers helm tests
    directory: chart/alertmanager/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
