# syntax=dhi.io/build:2-helm3

name: Prometheus AlertManager Helm chart 1.x
image: dhi.io/alertmanager-chart
variant: helm
tags:
  - 1.9.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_IMAGE_REFERENCE: dhi/alertmanager:0.30.1-debian13@sha256:2057993681fd6bdff1bb7e8e8397fcc6bfed477e813ea0148b01e48fe62fc5b2
  BUSYBOX_IMAGE_REFERENCE: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
  CHART_COMMIT_SHA: fcac966ef229709039b1610ee19afcf17104f082
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:a9247b60e56f190fb6de43042004c80b6ad903fe8df5becc513d89066aa3221c
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.88.1-debian13@sha256:8f97144b4f19800091e9509fe5b6a11054596e880dc6f933909b479cbdc36169
  SEMVER_MAJOR_MINOR_VERSION: "1.9"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.9.0
  VERSION: 1.9.0
contents:
  builds:
    - name: alertmanager
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:a9247b60e56f190fb6de43042004c80b6ad903fe8df5becc513d89066aa3221c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#alertmanager-1.9.0
            checksum: fcac966ef229709039b1610ee19afcf17104f082
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/alertmanager/
          with:
            chart:
              appRef: alertmanager
              description: Docker Hardened Images Helm chart for Prometheus AlertManager
              images:
                - name: alertmanager
                  ref: dhi/alertmanager:0.30.1-debian13@sha256:2057993681fd6bdff1bb7e8e8397fcc6bfed477e813ea0148b01e48fe62fc5b2
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.88.1-debian13@sha256:8f97144b4f19800091e9509fe5b6a11054596e880dc6f933909b479cbdc36169
                - name: busybox
                  ref: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2
              name: alertmanager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/alertmanager/
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: relocate test-connection template
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/alertmanager
          with:
            chart:
              mappings:
                - file: templates/tests/test-connection.yaml
                  raw: 'image: busybox'
                  replaceWith: 'image: dhi/busybox:1.37.0-alpine3.22@sha256:a1e4d4675dc1f8b4c9cdc0f62cb7e47623ca063c55665049a801d8d6d129f8b2'
            cmd: relocate
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/alertmanager
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: alertmanager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/alertmanager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alertmanager/config
