# syntax=dhi.io/build:1-helm3

name: Grafana Agent Helm chart 0.x
image: dhi.io/grafana-agent-chart
variant: helm
tags:
  - 0.44.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5ef5377b3d5421e754bff1028fd1ce4b3259cf5f
  CONFIGMAP_RELOAD_REFERENCE: dhi/configmap-reload:0.15.0-debian13@sha256:460342e1f209a4ec9f64e69b2393c2f83b4614e9f24ab3eea8abc321291e3be0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_AGENT_REFERENCE: dhi/grafana-agent:0.44.6-debian13@sha256:8c49c9a7f3644235b7001e91a4a41c699502386513881852cf279b3854882330
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  SEMVER_MAJOR_MINOR_VERSION: "0.44"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.44.2
  VERSION: 0.44.2
contents:
  builds:
    - name: grafana-agent
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana/agent.git#helm-chart/0.44.2
            checksum: 5ef5377b3d5421e754bff1028fd1ce4b3259cf5f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/grafana-agent
          with:
            chart:
              appRef: grafana-agent
              description: Docker Hardened Images Helm chart for Grafana Agent
              images:
                - name: grafana-agent
                  ref: dhi/grafana-agent:0.44.6-debian13@sha256:8c49c9a7f3644235b7001e91a4a41c699502386513881852cf279b3854882330
                - name: configmap-reload
                  ref: dhi/configmap-reload:0.15.0-debian13@sha256:460342e1f209a4ec9f64e69b2393c2f83b4614e9f24ab3eea8abc321291e3be0
              name: grafana-agent-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/agent
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/grafana-agent
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: grafana-agent
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: grafana-agent
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-agent/config
tests:
  - name: Run grafana-agent testcontainers helm tests
    directory: chart/grafana-agent/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
