# syntax=dhi.io/build:2-helm3

name: Kube State Metrics Helm chart 7.x
image: dhi.io/kube-state-metrics-chart
variant: helm
tags:
  - 7.0.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5524c8e9fa365cd2c12e76fb572fee3e419e55c7
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:ffc6f4caded4811f15f561336649019113250542f299f1d8282f3134663519f0
  KUBE_STATE_METRICS_REFERENCE: dhi/kube-state-metrics:2.17.0-debian13@sha256:0265699bb30c9c0a566220eaddf7c181b6a200c89e82fb74537c4549c8b9917f
  SEMVER_MAJOR_MINOR_VERSION: "7.0"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.0.1
  VERSION: 7.0.1
contents:
  builds:
    - name: kube-state-metrics-chart
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-state-metrics-7.0.1
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            chart:
              appRef: kube-state-metrics
              description: Docker Hardened Images Helm chart for Kube State Metrics
              images:
                - name: kube-state-metrics
                  ref: dhi/kube-state-metrics:2.17.0-debian13@sha256:0265699bb30c9c0a566220eaddf7c181b6a200c89e82fb74537c4549c8b9917f
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:ffc6f4caded4811f15f561336649019113250542f299f1d8282f3134663519f0
              name: kube-state-metrics-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-state-metrics
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-state-metrics/config
