# syntax=dhi.io/build:2-helm3

name: Kube State Metrics Helm chart 7.x
image: dhi.io/kube-state-metrics-chart
variant: helm
tags:
  - 7.1.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 254721e00ea50b46db0ae032c1873a4dca68d85a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:80e2a3669176937d7d4e36059f8fabbccf1182db401d26909fe776e5e8919660
  KUBE_STATE_METRICS_REFERENCE: dhi/kube-state-metrics:2.18.0-debian13@sha256:6a62d70108e06a5f67d0f7b50281e13687c6af9663158f7ef62c77c08484ca5c
  SEMVER_MAJOR_MINOR_VERSION: "7.1"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.1.0
  VERSION: 7.1.0
contents:
  builds:
    - name: kube-state-metrics-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-state-metrics-7.1.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            chart:
              appRef: kube-state-metrics
              description: Docker Hardened Images Helm chart for Kube State Metrics
              images:
                - name: kube-state-metrics
                  ref: dhi/kube-state-metrics:2.18.0-debian13@sha256:6a62d70108e06a5f67d0f7b50281e13687c6af9663158f7ef62c77c08484ca5c
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:80e2a3669176937d7d4e36059f8fabbccf1182db401d26909fe776e5e8919660
              name: kube-state-metrics-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-state-metrics
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-state-metrics/config
