# syntax=dhi.io/build:1-helm3

name: Valkey Helm chart 0.x
image: dhi.io/valkey-chart
variant: helm
tags:
  - 0.8.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: bce9499be2c7779513a26c5b10aaca7bdb87d647
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.80.1-debian13@sha256:42693be567877e7039800f88d9dbb54ae4926567d0aed6e9d5300e632f5c07e3
  SEMVER_MAJOR_MINOR_VERSION: "0.8"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.8.1
  VALKEY_REFERENCE: dhi/valkey:9.0.1-debian13@sha256:f1c6f7af37287cb36e8e73e7a8c9b07f160296dde9a6429a4b1e7948ef9d4297
  VERSION: 0.8.1
contents:
  builds:
    - name: valkey
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        files:
          - url: git+https://github.com/valkey-io/valkey-helm.git#v0.8.1
            checksum: bce9499be2c7779513a26c5b10aaca7bdb87d647
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/valkey
          with:
            chart:
              appRef: valkey
              description: Docker Hardened Images Helm chart for Valkey
              images:
                - name: valkey
                  ref: dhi/valkey:9.0.1-debian13@sha256:f1c6f7af37287cb36e8e73e7a8c9b07f160296dde9a6429a4b1e7948ef9d4297
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.80.1-debian13@sha256:42693be567877e7039800f88d9dbb54ae4926567d0aed6e9d5300e632f5c07e3
              name: valkey-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/valkey-io/valkey-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/valkey
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/valkey
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: valkey
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/valkey
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/valkey/config
tests:
  - name: Run valkey testcontainers helm tests
    directory: chart/valkey/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
