# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 82.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 82.0.2
platforms:
  - linux/amd64
vars:
  ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.89.0-debian13@sha256:3be30df3d91baf7fefb0075b8c4c96f5fa2d712938e6f934b6f1948fd2911d14
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.31.1-debian13@sha256:90a647781f3c91cc672ce864d265d14380dd9ef46ce9830e9dbe106f6419ee55
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:ee1f963dd3d57a59ae3f99fca81b06d19d1bef7c8289ff84001e0c65f39a8464
  CHART_COMMIT_SHA: 6b90ea26fbf197df08a9a28b87c3c80c1eae1d24
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:11.1.7@sha256:fea1952a2d77048302d87df05dafb8aefdb7571cdf1d2ba30f0a1af6c816f6d9
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.1.0@sha256:5bdd8744510d5beb285bea8e4bb84fca81b2a35c02bccb645e3370b2e190ec83
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.7.7-debian13@sha256:8d0735274181cd3d984f66299e81434898141ee745d06e30ce5068b216e0859d
  KUBECTL_REFERENCE: dhi/kubectl:1.35.0-debian13@sha256:9a348aa816c6192df2875ead343def0673ab4d5c335ef02af08f9568a099f5f9
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.51.1@sha256:0a00c3111f88572328ccf27eac5be3088b9e4898c4cf71a2df72656b9e8594f5
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2ed3c5e3d910d1f1e38eb00618e7c9a3c08e7cb11b8d6b127477a223f1c0a1b5
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.89.0-debian13@sha256:ca8efe793487702f384e209a7abade763d2b6eb58b024c5ddf5f17ef6f498972
  PROMETHEUS_REFERENCE: dhi/prometheus:3.9.1-debian13@sha256:6e7311111eec9d8fc4dca1d8e2d323081c072ea639ab9ea14d50da96faa0d1e6
  SEMVER_MAJOR_MINOR_VERSION: "82.0"
  SEMVER_MAJOR_VERSION: "82"
  SEMVER_VERSION: 82.0.2
  THANOS_REFERENCE: dhi/thanos:0.41.0-debian13@sha256:248d3e6cd93dfac46631567bdc4e308e8a36212e34adf52bea5e4230557e1725
  VERSION: 82.0.2
contents:
  builds:
    - name: kube-prometheus-stack-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-82.0.2
            checksum: 6b90ea26fbf197df08a9a28b87c3c80c1eae1d24
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.1.0@sha256:5bdd8744510d5beb285bea8e4bb84fca81b2a35c02bccb645e3370b2e190ec83
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.51.1@sha256:0a00c3111f88572328ccf27eac5be3088b9e4898c4cf71a2df72656b9e8594f5
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:11.1.7@sha256:fea1952a2d77048302d87df05dafb8aefdb7571cdf1d2ba30f0a1af6c816f6d9
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:ee1f963dd3d57a59ae3f99fca81b06d19d1bef7c8289ff84001e0c65f39a8464
                - name: kubectl
                  ref: dhi/kubectl:1.35.0-debian13@sha256:9a348aa816c6192df2875ead343def0673ab4d5c335ef02af08f9568a099f5f9
                - name: alertmanager
                  ref: dhi/alertmanager:0.31.1-debian13@sha256:90a647781f3c91cc672ce864d265d14380dd9ef46ce9830e9dbe106f6419ee55
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.89.0-debian13@sha256:3be30df3d91baf7fefb0075b8c4c96f5fa2d712938e6f934b6f1948fd2911d14
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.7.7-debian13@sha256:8d0735274181cd3d984f66299e81434898141ee745d06e30ce5068b216e0859d
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.89.0-debian13@sha256:ca8efe793487702f384e209a7abade763d2b6eb58b024c5ddf5f17ef6f498972
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2ed3c5e3d910d1f1e38eb00618e7c9a3c08e7cb11b8d6b127477a223f1c0a1b5
                - name: thanos
                  ref: dhi/thanos:0.41.0-debian13@sha256:248d3e6cd93dfac46631567bdc4e308e8a36212e34adf52bea5e4230557e1725
                - name: prometheus
                  ref: dhi/prometheus:3.9.1-debian13@sha256:6e7311111eec9d8fc4dca1d8e2d323081c072ea639ab9ea14d50da96faa0d1e6
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
