# syntax=dhi.io/build:1-debian13

name: Prometheus 3.x
image: dhi.io/prometheus
variant: runtime
tags:
  - "3.8"
  - 3.8.1
  - 3.8-debian13
  - 3.8.1-debian13
platforms:
  - linux/amd64
  - linux/arm64
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: ed753444ffec98097399d0cfa9073c70a840b812
  DEBIAN_EPOCH_MAJOR_MINOR_VERSION: "3.8"
  DEBIAN_EPOCH_MAJOR_VERSION: "3"
  DEBIAN_EPOCH_VERSION: 3.8.1
  GO_REF: dhi/golang:1.25.5-debian13-dev@sha256:8c2284d70af13cb934da5f05f5fa58a776aa963e88ebf542970ba09f4e3a0bbf
  GO_VERSION: 1.25.5
  NODE_REF: dhi/node:22.21.1-debian13-dev@sha256:9f2cc2b28df3ddcbf95208b8bd18df85fdc2ef63fc89b2a8bd2e9ec31731f873
  NODE_VERSION: 22.21.1
  RELEASE_TYPE: stable
  VERSION: 3.8.1
contents:
  packages:
    - '!base-files'
  builds:
    - name: prometheus
      uses: dhi.io/golang:1.25.5-debian13-dev@sha256:8c2284d70af13cb934da5f05f5fa58a776aa963e88ebf542970ba09f4e3a0bbf
      environment:
        USER: root
      contents:
        packages:
          - make
          - curl
          - bzip2
          - gzip
        files:
          - url: git+https://github.com/prometheus/prometheus.git#v3.8.1
            checksum: ed753444ffec98097399d0cfa9073c70a840b812
            path: /go/src/github.com/prometheus/prometheus
            spdx:
              name: prometheus
              version: 3.8.1
              packages:
                - name: prometheus
                  purl: pkg:dhi/prometheus@3.8.1
                  license: Apache-2.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:22.21.1-debian13-dev@sha256:9f2cc2b28df3ddcbf95208b8bd18df85fdc2ef63fc89b2a8bd2e9ec31731f873
            excludes:
              - usr/lib/ssl
            uid: 0
            gid: 0
      pipeline:
        - name: create SBOM for static assests
          work-dir: /go/src/github.com/prometheus/prometheus/web/ui/react-app
          runs: |
            set -eux -o pipefail

            npm sbom --omit=dev --omit=peer --package-lock-only --sbom-format=spdx > /opt/docker/sbom/prometheus/.prometheus-reactapp.spdx.json
        - name: compile static assets
          work-dir: /go/src/github.com/prometheus/prometheus
          privileged: true
          runs: |
            set -eux -o pipefail

            make assets npm_licenses assets-compress
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/prometheus/prometheus
          with:
            deps:
              - golang.org/x/crypto@v0.45.0
            download: true
        - name: go build
          work-dir: /go/src/github.com/prometheus/prometheus
          runs: |
            set -eux -o pipefail

            make plugins

            # Manually set version information used in "prometheus --version" output
            GOLDFLAGS="-X github.com/prometheus/common/version.Version=3.8.1
              -X github.com/prometheus/common/version.Revision=ed753444ffec98097399d0cfa9073c70a840b812
              -X github.com/prometheus/common/version.Branch=HEAD
              -X github.com/prometheus/common/version.BuildUser=$USER@$HOSTNAME
              -X github.com/prometheus/common/version.BuildDate=$(date -u "+%Y%m%d-%H:%M:%S" ${SOURCE_DATE_EPOCH:+-d @$SOURCE_DATE_EPOCH})
              -X github.com/prometheus/prometheus/version.Version=3.8.1
            "

            # Prometheus does use their own build tool, published separately at https://github.com/prometheus/promu,
            # but it's easy enough to build directly with go and set build metadata. If this becomes an issue,
            # `make common-build` will do the job.
            CGO_ENABLED=0 go build \
              -mod=readonly \
              -ldflags "$GOLDFLAGS" \
              -tags netgo,builtinassets,stringlabels \
              ./cmd/prometheus

            CGO_ENABLED=0 go build \
              -mod=readonly \
              -ldflags "$GOLDFLAGS" \
              ./cmd/promtool
        - name: install
          work-dir: /go/src/github.com/prometheus/prometheus
          runs: |
            set -eux -o pipefail

            mkdir -p ${target.dir}/usr/local/bin
            cp ./prometheus ./promtool ${target.dir}/usr/local/bin/

            mkdir -p ${target.dir}/etc/prometheus
            cp ./documentation/examples/prometheus.yml ${target.dir}/etc/prometheus/
      outputs:
        - source: ${target.dir}/usr/local/bin/
          target: /usr/local/bin/
          uid: 0
          gid: 0
        - source: ${target.dir}/etc/prometheus
          target: /etc/prometheus
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/prometheus
          target: /opt/docker/sbom/prometheus
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
paths:
  - type: directory
    path: /var/prometheus
    uid: 65532
    gid: 65532
    mode: "0755"
annotations:
  org.opencontainers.image.description: A minimal Prometheus image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - prometheus
cmd:
  - --config.file=/etc/prometheus/prometheus.yml
  - --storage.tsdb.path=/var/prometheus
ports:
  - 9090/tcp
tests:
  - name: Run testcontainers tests
    directory: image/prometheus/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
