image:
  repository: ${opentelemetry-collector.registry}/${opentelemetry-collector.repository}
  tag: ${opentelemetry-collector.tag}
  digest: ${opentelemetry-collector.digest}

# Valid values are "daemonset", "deployment", and "statefulset".
mode: deployment

podSecurityContext:
  fsGroup: 65532
securityContext:
  runAsUser: 65532
  runAsNonRoot: true
  runAsGroup: 65532
