# syntax=dhi.io/build:1-helm3

name: Prometheus Node Exporter Helm chart 4.x
image: dhi.io/node-exporter-chart
variant: helm
tags:
  - 4.49.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 119c33d2ae6cc4817947e604f464225ede78f9d6
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.20.1-debian13@sha256:46ce1191c0ccf6687672664cbcec028324f55d54eed3c433c3c85bf2bdf1c242
  NODE_EXPORTER_REFERENCE: dhi/node-exporter:1.10.2-debian13@sha256:9015be6c443289c5aa500d078a2cfa37ff71e27fa63904fd935bf1a9b351b19f
  SEMVER_MAJOR_MINOR_VERSION: "4.49"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.49.2
  VERSION: 4.49.2
contents:
  builds:
    - name: node-exporter-chart
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-node-exporter-4.49.2
            checksum: 119c33d2ae6cc4817947e604f464225ede78f9d6
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            chart:
              appRef: node-exporter
              description: Docker Hardened Images Helm chart for Prometheus Node Exporter
              images:
                - name: node-exporter
                  ref: dhi/node-exporter:1.10.2-debian13@sha256:9015be6c443289c5aa500d078a2cfa37ff71e27fa63904fd935bf1a9b351b19f
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.20.1-debian13@sha256:46ce1191c0ccf6687672664cbcec028324f55d54eed3c433c3c85bf2bdf1c242
              name: node-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-node-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/node-exporter/config
tests:
  - name: Run node-exporter testcontainers helm tests
    directory: chart/node-exporter/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
