# syntax=dhi.io/build:2-helm3

name: Prometheus Node Exporter Helm chart 4.x
image: dhi.io/node-exporter-chart
variant: helm
tags:
  - 4.51.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 70b17626154c5445a0f48b3e8d41ee62a535c467
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:80e2a3669176937d7d4e36059f8fabbccf1182db401d26909fe776e5e8919660
  NODE_EXPORTER_REFERENCE: dhi/node-exporter:1.10.2-debian13@sha256:de0efce62e1b7edaa58bc8db6be1dce4a8e6665a85c597b355378fa38320272e
  SEMVER_MAJOR_MINOR_VERSION: "4.51"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.51.1
  VERSION: 4.51.1
contents:
  builds:
    - name: node-exporter-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-node-exporter-4.51.1
            checksum: 70b17626154c5445a0f48b3e8d41ee62a535c467
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            chart:
              appRef: node-exporter
              description: Docker Hardened Images Helm chart for Prometheus Node Exporter
              images:
                - name: node-exporter
                  ref: dhi/node-exporter:1.10.2-debian13@sha256:de0efce62e1b7edaa58bc8db6be1dce4a8e6665a85c597b355378fa38320272e
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:80e2a3669176937d7d4e36059f8fabbccf1182db401d26909fe776e5e8919660
              name: node-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-node-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/node-exporter/config
