# syntax=dhi.io/build:2-helm3

name: Prometheus Node Exporter Helm chart 4.x
image: dhi.io/node-exporter-chart
variant: helm
tags:
  - 4.51.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 27e215f2905bcfcf2b04d053a4d2c9c0330bb48d
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.20.1-debian13@sha256:29a3c445c1f31f57b3db9fd40efef59e5281c7cd18c0728101a5425ebf8ae638
  NODE_EXPORTER_REFERENCE: dhi/node-exporter:1.10.2-debian13@sha256:aa5b19efc4b738bc2b37e8b9349de3d3b13398eaeab16e0b876fda43b107055d
  SEMVER_MAJOR_MINOR_VERSION: "4.51"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.51.0
  VERSION: 4.51.0
contents:
  builds:
    - name: node-exporter-chart
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-node-exporter-4.51.0
            checksum: 27e215f2905bcfcf2b04d053a4d2c9c0330bb48d
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            chart:
              appRef: node-exporter
              description: Docker Hardened Images Helm chart for Prometheus Node Exporter
              images:
                - name: node-exporter
                  ref: dhi/node-exporter:1.10.2-debian13@sha256:aa5b19efc4b738bc2b37e8b9349de3d3b13398eaeab16e0b876fda43b107055d
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.20.1-debian13@sha256:29a3c445c1f31f57b3db9fd40efef59e5281c7cd18c0728101a5425ebf8ae638
              name: node-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-node-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/node-exporter/config
