# syntax=dhi.io/build:2-helm3

name: Kubernetes Cluster Autoscaler Helm chart 9.x
image: dhi.io/kubernetes-cluster-autoscaler-chart
variant: helm
tags:
  - 9.55.1
platforms:
  - linux/amd64
vars:
  AUTOSCALER_REFERENCE: dhi/kubernetes-cluster-autoscaler:1.34.3-debian13@sha256:52c676bf33b8fd27689bf4cb5b1d2e54b9194bcdbe415ca1355386aaac7560ff
  CHART_COMMIT_SHA: 4063e80431285255a3c8c0f03bad4a2ef581048a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  SEMVER_MAJOR_MINOR_VERSION: "9.55"
  SEMVER_MAJOR_VERSION: "9"
  SEMVER_VERSION: 9.55.1
  VERSION: 9.55.1
contents:
  builds:
    - name: kubernetes-cluster-autoscaler
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/kubernetes/autoscaler.git#cluster-autoscaler-chart-9.55.1
            checksum: 4063e80431285255a3c8c0f03bad4a2ef581048a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/cluster-autoscaler/charts/cluster-autoscaler
          with:
            chart:
              appRef: kubernetes-cluster-autoscaler
              description: Docker Hardened Images Helm chart for kubernetes-cluster-autoscaler
              images:
                - name: kubernetes-cluster-autoscaler
                  ref: dhi/kubernetes-cluster-autoscaler:1.34.3-debian13@sha256:52c676bf33b8fd27689bf4cb5b1d2e54b9194bcdbe415ca1355386aaac7560ff
              name: kubernetes-cluster-autoscaler-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kubernetes/autoscaler
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/cluster-autoscaler/charts/cluster-autoscaler
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/cluster-autoscaler/charts
          with:
            chart: cluster-autoscaler
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/cluster-autoscaler/charts
          with:
            chart: cluster-autoscaler
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kubernetes-cluster-autoscaler/config
