# syntax=dhi.io/build:2-helm3

name: Grafana Helm chart 11.x
image: dhi.io/grafana-chart
variant: helm
tags:
  - 11.1.6
platforms:
  - linux/amd64
vars:
  BATS_REFERENCE: dhi/bats:1.13.0-debian13@sha256:d4e3d771225f4becb87d5e152e4c9c28d74a8d9595cda5cd310ce192cd310cb9
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:ee1f963dd3d57a59ae3f99fca81b06d19d1bef7c8289ff84001e0c65f39a8464
  CHART_COMMIT_SHA: 2e62c4ff0b82726165f28e61d45d1537d3d0765b
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:571b666b14e3a39be196b9b8118d2a81a1d09a206139f6e3299e2dc587725e01
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_IMAGE_RENDERER_REFERENCE: dhi/grafana-image-renderer:5.5.1-debian13@sha256:81c61c8f8b01d7b957135a6383980eba57eb1ff9d6414733efa7ea0f08bb8637
  GRAFANA_REFERENCE: dhi/grafana:12.3.3-debian13@sha256:db795f3e9a035fba158e59f13ebbd0b6cb3698829b9504660cfe375601d461cd
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.5.1-debian13@sha256:0df9e24ad6010427ac81fd51f25bee0c420404fc9f7d6ce97997c7ec53ec1469
  SEMVER_MAJOR_MINOR_VERSION: "11.1"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.1.6
  VERSION: 11.1.6
contents:
  builds:
    - name: grafana
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#grafana-11.1.6
            checksum: 2e62c4ff0b82726165f28e61d45d1537d3d0765b
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            chart:
              appRef: grafana
              description: Docker Hardened Images Helm chart for Grafana
              images:
                - name: grafana
                  ref: dhi/grafana:12.3.3-debian13@sha256:db795f3e9a035fba158e59f13ebbd0b6cb3698829b9504660cfe375601d461cd
                - name: grafana-image-renderer
                  ref: dhi/grafana-image-renderer:5.5.1-debian13@sha256:81c61c8f8b01d7b957135a6383980eba57eb1ff9d6414733efa7ea0f08bb8637
                - name: bats
                  ref: dhi/bats:1.13.0-debian13@sha256:d4e3d771225f4becb87d5e152e4c9c28d74a8d9595cda5cd310ce192cd310cb9
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:ee1f963dd3d57a59ae3f99fca81b06d19d1bef7c8289ff84001e0c65f39a8464
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:571b666b14e3a39be196b9b8118d2a81a1d09a206139f6e3299e2dc587725e01
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.5.1-debian13@sha256:0df9e24ad6010427ac81fd51f25bee0c420404fc9f7d6ce97997c7ec53ec1469
              name: grafana-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana/config
