# syntax=dhi.io/build:2-helm3

name: Grafana Operator Helm chart 5.x
image: dhi.io/grafana-operator-chart
variant: helm
tags:
  - 5.21.4
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 23c0a1a686b5651ff486f9c1c424ca07fc1023c2
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_OPERATOR_REFERENCE: dhi/grafana-operator:5.21.4-debian13@sha256:728bf47ef064b297f933c27016184fc5ac38fc238f6bea0b3aa4a1152fa02f06
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  SEMVER_MAJOR_MINOR_VERSION: "5.21"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.21.4
  VERSION: 5.21.4
contents:
  builds:
    - name: grafana-operator-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/grafana/grafana-operator.git#v5.21.4
            checksum: 23c0a1a686b5651ff486f9c1c424ca07fc1023c2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/grafana-operator
          with:
            chart:
              appRef: grafana-operator
              description: Docker Hardened Images Helm chart for Grafana Operator
              images:
                - name: grafana-operator
                  ref: dhi/grafana-operator:5.21.4-debian13@sha256:728bf47ef064b297f933c27016184fc5ac38fc238f6bea0b3aa4a1152fa02f06
              name: grafana-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/grafana-operator
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/grafana-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          privileged: true
          with:
            chart: grafana-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: grafana-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: grafana-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-operator/config
