# syntax=dhi.io/build:2-helm3

name: Redis Helm chart 23.x
image: dhi.io/redis-chart
variant: helm
tags:
  - 23.0.5
platforms:
  - linux/amd64
vars:
  BASH_REFERENCE: dhi/bash:5.2.37-debian13@sha256:f4a446ed86875dce4b449b082ad5742a292a5222238429ca23e22335c0bd4466
  CHART_COMMIT_SHA: 52f91605180a633cfd40613dc84b0f71f23f43d6
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-debian13@sha256:4764749d32d0312dc2d9f82b3309d691cea656f098810caaaa9e0156714c0da0
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.80.1-debian13-compat@sha256:ea39f5746ca751137bb4a6518a57b0b9cde9effd6e53fbf5e1e4ebc213ab746f
  REDIS_REFERENCE: dhi/redis:8.2.3-debian13-compat@sha256:5f091601d2ee04bd5297e2783e9a97ae99ac29f0619f4c5d7837fefd91948bed
  SEMVER_MAJOR_MINOR_VERSION: "23.0"
  SEMVER_MAJOR_VERSION: "23"
  SEMVER_VERSION: 23.0.5
  VERSION: 23.0.5
contents:
  builds:
    - name: redis
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
      contents:
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#redis/23.0.5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            chart:
              appRef: redis
              description: Docker Hardened Images Helm chart for Redis
              images:
                - name: redis
                  ref: dhi/redis:8.2.3-debian13-compat@sha256:5f091601d2ee04bd5297e2783e9a97ae99ac29f0619f4c5d7837fefd91948bed
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.80.1-debian13-compat@sha256:ea39f5746ca751137bb4a6518a57b0b9cde9effd6e53fbf5e1e4ebc213ab746f
                - name: bash
                  ref: dhi/bash:5.2.37-debian13@sha256:f4a446ed86875dce4b449b082ad5742a292a5222238429ca23e22335c0bd4466
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-debian13@sha256:4764749d32d0312dc2d9f82b3309d691cea656f098810caaaa9e0156714c0da0
              name: redis-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/redis
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: redis
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/redis
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/redis/config
