# syntax=dhi.io/build:2-helm3

name: Redis Helm chart 23.x
image: dhi.io/redis-chart
variant: helm
tags:
  - 23.0.5
platforms:
  - linux/amd64
vars:
  BASH_REFERENCE: dhi/bash:5.2.37-debian13@sha256:08916a31cadcc5560f7429cb78aedcc9287977a74401bbf80dcb52f0fae8a4aa
  CHART_COMMIT_SHA: 52f91605180a633cfd40613dc84b0f71f23f43d6
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:bbd34d906c2bce0070a2daa2c7858393feb6c51862fb139a6e1afc923b6e15b0
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-debian13@sha256:8cf7b277f3774e4cee259a8c6107c59fa512a0991a37f0838502b725736db088
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.80.2-debian13-compat@sha256:095e7cfd3f29fd762077809d70859a45710f1e43ba581cfc43526cf53031967c
  REDIS_REFERENCE: dhi/redis:8.2.3-debian13-compat@sha256:3daa485ae462b2769c0b1b584b08767ba4ea50401ae61fd4264f160b5c2cf7c0
  SEMVER_MAJOR_MINOR_VERSION: "23.0"
  SEMVER_MAJOR_VERSION: "23"
  SEMVER_VERSION: 23.0.5
  VERSION: 23.0.5
contents:
  builds:
    - name: redis
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:bbd34d906c2bce0070a2daa2c7858393feb6c51862fb139a6e1afc923b6e15b0
      contents:
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#redis/23.0.5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            chart:
              appRef: redis
              description: Docker Hardened Images Helm chart for Redis
              images:
                - name: redis
                  ref: dhi/redis:8.2.3-debian13-compat@sha256:3daa485ae462b2769c0b1b584b08767ba4ea50401ae61fd4264f160b5c2cf7c0
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.80.2-debian13-compat@sha256:095e7cfd3f29fd762077809d70859a45710f1e43ba581cfc43526cf53031967c
                - name: bash
                  ref: dhi/bash:5.2.37-debian13@sha256:08916a31cadcc5560f7429cb78aedcc9287977a74401bbf80dcb52f0fae8a4aa
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-debian13@sha256:8cf7b277f3774e4cee259a8c6107c59fa512a0991a37f0838502b725736db088
              name: redis-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/redis
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: redis
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/redis
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/redis/config
