# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Cluster Helm chart 0.x
image: dhi.io/victoriametrics-cluster-chart
variant: helm
tags:
  - 0.34.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5c1debc9b82344b174477e045a2d400b55a4edee
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
  SEMVER_MAJOR_MINOR_VERSION: "0.34"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.34.0
  VERSION: 0.34.0
  VMAUTH_REFERENCE: dhi/victoriametrics-vmauth:1.135.0-debian13@sha256:bb864b7f29f3444f064befec87a8f150d48565ab00ee6119d4ab42000b48f344
  VMINSERT_REFERENCE: dhi/victoriametrics-vminsert:1.135.0-debian13@sha256:ffe8f266cb012b4fbf8dc8a36146aa36e38a548b2f6eb5460a7f629262ffa59f
  VMSELECT_REFERENCE: dhi/victoriametrics-vmselect:1.135.0-debian13@sha256:b56950317cdb279636a55cd30a903b81466851c8559ee2213cbb400ccf2eef1f
  VMSTORAGE_REFERENCE: dhi/victoriametrics-vmstorage:1.135.0-debian13@sha256:64f5d7fc4b920d82ebe88fb87941a1ac695f35626741c95562eb04b550f7251f
contents:
  builds:
    - name: victoriametrics-cluster-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-cluster-0.34.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            chart:
              appRef: victoriametrics-vmselect
              description: Docker Hardened Images Helm chart for VictoriaMetrics Cluster
              images:
                - name: victoriametrics-vmselect
                  ref: dhi/victoriametrics-vmselect:1.135.0-debian13@sha256:b56950317cdb279636a55cd30a903b81466851c8559ee2213cbb400ccf2eef1f
                - name: victoriametrics-vmstorage
                  ref: dhi/victoriametrics-vmstorage:1.135.0-debian13@sha256:64f5d7fc4b920d82ebe88fb87941a1ac695f35626741c95562eb04b550f7251f
                - name: victoriametrics-vminsert
                  ref: dhi/victoriametrics-vminsert:1.135.0-debian13@sha256:ffe8f266cb012b4fbf8dc8a36146aa36e38a548b2f6eb5460a7f629262ffa59f
                - name: victoriametrics-vmauth
                  ref: dhi/victoriametrics-vmauth:1.135.0-debian13@sha256:bb864b7f29f3444f064befec87a8f150d48565ab00ee6119d4ab42000b48f344
              name: victoriametrics-cluster-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update sidecar values
          uses: yq/patch@v1
          with:
            file: ${source.dir}/helm-charts/charts/victoria-metrics-cluster/values-sidecar.yaml
            patches:
              - .extraContainers[0].image = "dhi/victoriametrics-vmauth:1.135.0-debian13@sha256:bb864b7f29f3444f064befec87a8f150d48565ab00ee6119d4ab42000b48f344"
              - .extraContainers[0].securityContext.enabled = true
              - .extraContainers[0].securityContext.runAsNonRoot = true
              - .extraContainers[0].securityContext.runAsUser = 65532
              - .extraContainers[0].securityContext.runAsGroup = 65532
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for victoriametrics/vmbackupmanager
            sed -i '/- name: vmbackupmanager/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/vmstorage-server.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-cluster
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-cluster/config
