# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Cluster Helm chart 0.x
image: dhi.io/victoriametrics-cluster-chart
variant: helm
tags:
  - 0.33.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: fb1f9c11825a53d3a4a8ed89724977edcdf19382
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
  SEMVER_MAJOR_MINOR_VERSION: "0.33"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.33.0
  VERSION: 0.33.0
  VMAUTH_REFERENCE: dhi/victoriametrics-vmauth:1.134.0-debian13@sha256:05bbea1e255caaa10b319b130c825620497c3af76dfa071a17cc0182728ed3e3
  VMINSERT_REFERENCE: dhi/victoriametrics-vminsert:1.134.0-debian13@sha256:33cc0a780ea7453fb0227ef8290706ddb08b189d6b1b99d52e7caf4debaf8246
  VMSELECT_REFERENCE: dhi/victoriametrics-vmselect:1.134.0-debian13@sha256:14602ce7f23bacc049603113ee808ce798adb73a080f9a26d25cf3740b45610d
  VMSTORAGE_REFERENCE: dhi/victoriametrics-vmstorage:1.134.0-debian13@sha256:25d3b2d22f15d94b8d42931657f6ed400c9c8653dab0fd784b51d8dc93e03431
contents:
  builds:
    - name: victoriametrics-cluster-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-cluster-0.33.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            chart:
              appRef: victoriametrics-vmselect
              description: Docker Hardened Images Helm chart for VictoriaMetrics Cluster
              images:
                - name: victoriametrics-vmselect
                  ref: dhi/victoriametrics-vmselect:1.134.0-debian13@sha256:14602ce7f23bacc049603113ee808ce798adb73a080f9a26d25cf3740b45610d
                - name: victoriametrics-vmstorage
                  ref: dhi/victoriametrics-vmstorage:1.134.0-debian13@sha256:25d3b2d22f15d94b8d42931657f6ed400c9c8653dab0fd784b51d8dc93e03431
                - name: victoriametrics-vminsert
                  ref: dhi/victoriametrics-vminsert:1.134.0-debian13@sha256:33cc0a780ea7453fb0227ef8290706ddb08b189d6b1b99d52e7caf4debaf8246
                - name: victoriametrics-vmauth
                  ref: dhi/victoriametrics-vmauth:1.134.0-debian13@sha256:05bbea1e255caaa10b319b130c825620497c3af76dfa071a17cc0182728ed3e3
              name: victoriametrics-cluster-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update sidecar values
          uses: yq/patch@v1
          with:
            file: ${source.dir}/helm-charts/charts/victoria-metrics-cluster/values-sidecar.yaml
            patches:
              - .extraContainers[0].image = "dhi/victoriametrics-vmauth:1.134.0-debian13@sha256:05bbea1e255caaa10b319b130c825620497c3af76dfa071a17cc0182728ed3e3"
              - .extraContainers[0].securityContext.enabled = true
              - .extraContainers[0].securityContext.runAsNonRoot = true
              - .extraContainers[0].securityContext.runAsUser = 65532
              - .extraContainers[0].securityContext.runAsGroup = 65532
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for victoriametrics/vmbackupmanager
            sed -i '/- name: vmbackupmanager/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/vmstorage-server.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-cluster
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-cluster/config
