# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Cluster Helm chart 0.x
image: dhi.io/victoriametrics-cluster-chart
variant: helm
tags:
  - 0.32.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: fe149b12908348a67e251d544d619c6e6ead13a9
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
  SEMVER_MAJOR_MINOR_VERSION: "0.32"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.32.0
  VERSION: 0.32.0
  VMAUTH_REFERENCE: dhi/victoriametrics-vmauth:1.133.0-debian13@sha256:28eeb6430153d66f66fc1063843bde3c1727aadf67592b2cb029c91916b2ac8f
  VMINSERT_REFERENCE: dhi/victoriametrics-vminsert:1.133.0-debian13@sha256:5f88143eba524c8c3f14e4b3f280fae9ad400cce43478b7a9dc6923ef840f1ea
  VMSELECT_REFERENCE: dhi/victoriametrics-vmselect:1.133.0-debian13@sha256:fdbad0dd80ca1efa01e41c2bb9adfa79616ae39a34e6736d3315025a73dacde7
  VMSTORAGE_REFERENCE: dhi/victoriametrics-vmstorage:1.133.0-debian13@sha256:5f73386b9a39f92e19cbb45a4e578e4e8fce32b914533a953bbca58a656c03e0
contents:
  builds:
    - name: victoriametrics-cluster-chart
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-cluster-0.32.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            chart:
              appRef: victoriametrics-vmselect
              description: Docker Hardened Images Helm chart for VictoriaMetrics Cluster
              images:
                - name: victoriametrics-vmselect
                  ref: dhi/victoriametrics-vmselect:1.133.0-debian13@sha256:fdbad0dd80ca1efa01e41c2bb9adfa79616ae39a34e6736d3315025a73dacde7
                - name: victoriametrics-vmstorage
                  ref: dhi/victoriametrics-vmstorage:1.133.0-debian13@sha256:5f73386b9a39f92e19cbb45a4e578e4e8fce32b914533a953bbca58a656c03e0
                - name: victoriametrics-vminsert
                  ref: dhi/victoriametrics-vminsert:1.133.0-debian13@sha256:5f88143eba524c8c3f14e4b3f280fae9ad400cce43478b7a9dc6923ef840f1ea
                - name: victoriametrics-vmauth
                  ref: dhi/victoriametrics-vmauth:1.133.0-debian13@sha256:28eeb6430153d66f66fc1063843bde3c1727aadf67592b2cb029c91916b2ac8f
              name: victoriametrics-cluster-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update sidecar values
          uses: yq/patch@v1
          with:
            file: ${source.dir}/helm-charts/charts/victoria-metrics-cluster/values-sidecar.yaml
            patches:
              - .extraContainers[0].image = "dhi/victoriametrics-vmauth:1.133.0-debian13@sha256:28eeb6430153d66f66fc1063843bde3c1727aadf67592b2cb029c91916b2ac8f"
              - .extraContainers[0].securityContext.enabled = true
              - .extraContainers[0].securityContext.runAsNonRoot = true
              - .extraContainers[0].securityContext.runAsUser = 65532
              - .extraContainers[0].securityContext.runAsGroup = 65532
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for victoriametrics/vmbackupmanager
            sed -i '/- name: vmbackupmanager/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/vmstorage-server.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-cluster
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-cluster/config
