# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Cluster Helm chart 0.x
image: dhi.io/victoriametrics-cluster-chart
variant: helm
tags:
  - 0.34.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5c1debc9b82344b174477e045a2d400b55a4edee
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
  SEMVER_MAJOR_MINOR_VERSION: "0.34"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.34.0
  VERSION: 0.34.0
  VMAUTH_REFERENCE: dhi/victoriametrics-vmauth:1.135.0-debian13@sha256:571ab78a62292419b29f9676026c201aeb593e476501766562e8310ed9ed6fc3
  VMINSERT_REFERENCE: dhi/victoriametrics-vminsert:1.135.0-debian13@sha256:d8a45aebefcafde26bf0f8117080ea1372943d6ce63ad81fd3705bb154800ff0
  VMSELECT_REFERENCE: dhi/victoriametrics-vmselect:1.135.0-debian13@sha256:5d298301d6cdf1489c97b13795831a15ee01ef88643a351827a55c2ca85ade6a
  VMSTORAGE_REFERENCE: dhi/victoriametrics-vmstorage:1.135.0-debian13@sha256:8710617ef6cd3a652bee1869ea777c57dffa64e3ec9ea498fdcfd92304d32e88
contents:
  builds:
    - name: victoriametrics-cluster-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-cluster-0.34.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            chart:
              appRef: victoriametrics-vmselect
              description: Docker Hardened Images Helm chart for VictoriaMetrics Cluster
              images:
                - name: victoriametrics-vmselect
                  ref: dhi/victoriametrics-vmselect:1.135.0-debian13@sha256:5d298301d6cdf1489c97b13795831a15ee01ef88643a351827a55c2ca85ade6a
                - name: victoriametrics-vmstorage
                  ref: dhi/victoriametrics-vmstorage:1.135.0-debian13@sha256:8710617ef6cd3a652bee1869ea777c57dffa64e3ec9ea498fdcfd92304d32e88
                - name: victoriametrics-vminsert
                  ref: dhi/victoriametrics-vminsert:1.135.0-debian13@sha256:d8a45aebefcafde26bf0f8117080ea1372943d6ce63ad81fd3705bb154800ff0
                - name: victoriametrics-vmauth
                  ref: dhi/victoriametrics-vmauth:1.135.0-debian13@sha256:571ab78a62292419b29f9676026c201aeb593e476501766562e8310ed9ed6fc3
              name: victoriametrics-cluster-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update sidecar values
          uses: yq/patch@v1
          with:
            file: ${source.dir}/helm-charts/charts/victoria-metrics-cluster/values-sidecar.yaml
            patches:
              - .extraContainers[0].image = "dhi/victoriametrics-vmauth:1.135.0-debian13@sha256:571ab78a62292419b29f9676026c201aeb593e476501766562e8310ed9ed6fc3"
              - .extraContainers[0].securityContext.enabled = true
              - .extraContainers[0].securityContext.runAsNonRoot = true
              - .extraContainers[0].securityContext.runAsUser = 65532
              - .extraContainers[0].securityContext.runAsGroup = 65532
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for victoriametrics/vmbackupmanager
            sed -i '/- name: vmbackupmanager/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/vmstorage-server.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-cluster
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-cluster/config
