# syntax=dhi.io/build:2-helm3

name: Metrics Server Helm chart 3.x
image: dhi.io/metrics-server-chart
variant: helm
tags:
  - 3.13.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 1a64100c33acf2d7dfa4439f20c75bc64d86983f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
  METRICS_SERVER_REFERENCE: dhi/metrics-server:0.8.0-debian13@sha256:283b993f8a098a40e94076d18f0ad3eff596ef95b57276b0a977d07cdd78fe79
  SEMVER_MAJOR_MINOR_VERSION: "3.13"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.13.0
  VERSION: 3.13.0
contents:
  builds:
    - name: metrics-server-chart
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
      contents:
        files:
          - url: git+https://github.com/kubernetes-sigs/metrics-server.git#metrics-server-helm-chart-3.13.0
            checksum: 1a64100c33acf2d7dfa4439f20c75bc64d86983f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/metrics-server
          with:
            chart:
              appRef: metrics-server
              description: Docker Hardened Images Helm chart for Metrics Server
              images:
                - name: metrics-server
                  ref: dhi/metrics-server:0.8.0-debian13@sha256:283b993f8a098a40e94076d18f0ad3eff596ef95b57276b0a977d07cdd78fe79
              name: metrics-server-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kubernetes-sigs/metrics-server
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/metrics-server
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: metrics-server
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: metrics-server
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: metrics-server
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/metrics-server/config
