image:
  registry: ${strimzi-operator.registry}
  repository: ${strimzi-operator.repository}
  name:
  tag: ${strimzi-operator.tag}@${strimzi-operator.digest}
kafka:
  image:
    registry: ${strimzi-kafka.registry}
    repository: ${strimzi-kafka.repository}
    name:
    tag: ${strimzi-kafka.tag}@${strimzi-kafka.digest}
kafkaConnect:
  image:
    registry: ${strimzi-kafka.registry}
    repository: ${strimzi-kafka.repository}
    name:
    tag: ${strimzi-kafka.tag}@${strimzi-kafka.digest}
topicOperator:
  image:
    registry: ${strimzi-operator.registry}
    repository: ${strimzi-operator.repository}
    name:
    tag: ${strimzi-operator.tag}@${strimzi-operator.digest}
userOperator:
  image:
    registry: ${strimzi-operator.registry}
    repository: ${strimzi-operator.repository}
    name:
    tag: ${strimzi-operator.tag}@${strimzi-operator.digest}
kafkaInit:
  image:
    registry: ${strimzi-operator.registry}
    repository: ${strimzi-operator.repository}
    name:
    tag: ${strimzi-operator.tag}@${strimzi-operator.digest}
kafkaBridge:
  image:
    registry: ""
    repository:
    name: kafka-bridge
    tag: 0.33.1
kafkaExporter:
  image:
    registry: ${strimzi-kafka.registry}
    repository: ${strimzi-kafka.repository}
    name:
    tag: ${strimzi-kafka.tag}@${strimzi-kafka.digest}
kafkaMirrorMaker2:
  image:
    registry: ${strimzi-kafka.registry}
    repository: ${strimzi-kafka.repository}
    name:
    tag: ${strimzi-kafka.tag}@${strimzi-kafka.digest}
cruiseControl:
  image:
    registry: ${strimzi-kafka.registry}
    repository: ${strimzi-kafka.repository}
    name:
    tag: ${strimzi-kafka.tag}@${strimzi-kafka.digest}
kanikoExecutor:
  image:
    registry: ""
    repository: ""
    name: kaniko-executor
    tag: ""
buildah:
  image:
    registry: ""
    repository: ""
    name: buildah
    tag: ""
mavenBuilder:
  image:
    registry: ""
    repository: ""
    name: maven-builder
    tag: ""

podSecurityContext:
  fsGroup: 65532
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
