# syntax=dhi.io/build:2-helm3

name: Vector Helm chart 0.x
image: dhi.io/vector-chart
variant: helm
tags:
  - 0.49.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 9474ee81b8f38debbc65df650d9a044d4d9b8804
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HAPROXY_REFERENCE: dhi/haproxy:3.0.14-debian13@sha256:fbe08eb3353cb4376e0912d95903e59365af1c670bbe1a1ae8ddf10cc51835c4
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
  SEMVER_MAJOR_MINOR_VERSION: "0.49"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.49.0
  VECTOR_REFERENCE: dhi/vector:0.52.0-debian13@sha256:8750a2a181d86ba34fa00e13c2f4ae40cd9c9d43a8bb6d8e10c9e1b76b4e2a08
  VERSION: 0.49.0
contents:
  builds:
    - name: vector-chart
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
      contents:
        files:
          - url: git+https://github.com/vectordotdev/helm-charts.git#vector-0.49.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            chart:
              appRef: vector
              description: Docker Hardened Images Helm chart for Vector
              images:
                - name: vector
                  ref: dhi/vector:0.52.0-debian13@sha256:8750a2a181d86ba34fa00e13c2f4ae40cd9c9d43a8bb6d8e10c9e1b76b4e2a08
                - name: haproxy
                  ref: dhi/haproxy:3.0.14-debian13@sha256:fbe08eb3353cb4376e0912d95903e59365af1c670bbe1a1ae8ddf10cc51835c4
              name: vector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vectordotdev/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: vector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vector/config
