# syntax=dhi.io/build:2-helm3

name: Vector Helm chart 0.x
image: dhi.io/vector-chart
variant: helm
tags:
  - 0.50.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ebe4be6421a9aaeadff0f0ab77ae2f29312af2f0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HAPROXY_REFERENCE: dhi/haproxy:3.0.15-debian13@sha256:ed639c1bd643df71e1092e54a8260628dcce9869efc51fc0c376ea3d5ac19aa8
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
  SEMVER_MAJOR_MINOR_VERSION: "0.50"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.50.0
  VECTOR_REFERENCE: dhi/vector:0.52.0-debian13@sha256:7eb6d3f9fc6c7be0982a6a4a8a2aedb4c47eba89c69a1dda21b7f4f31e4d843d
  VERSION: 0.50.0
contents:
  builds:
    - name: vector-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
      contents:
        files:
          - url: git+https://github.com/vectordotdev/helm-charts.git#vector-0.50.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            chart:
              appRef: vector
              description: Docker Hardened Images Helm chart for Vector
              images:
                - name: vector
                  ref: dhi/vector:0.52.0-debian13@sha256:7eb6d3f9fc6c7be0982a6a4a8a2aedb4c47eba89c69a1dda21b7f4f31e4d843d
                - name: haproxy
                  ref: dhi/haproxy:3.0.15-debian13@sha256:ed639c1bd643df71e1092e54a8260628dcce9869efc51fc0c376ea3d5ac19aa8
              name: vector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vectordotdev/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: vector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vector/config
