# syntax=dhi.io/build:2-debian13

name: Prometheus Statsd Exporter 0.28.x
image: dhi.io/prometheus-statsd-exporter
variant: runtime
tags:
  - "0"
  - "0.28"
  - 0.28.0
  - 0-debian13
  - 0.28-debian13
  - 0.28.0-debian13
platforms:
  - linux/amd64
  - linux/arm64
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: c0a390a2c43f77863278615b47d46e886bdca726
  GOLANG_REFERENCE: dhi/golang:1.24.11-debian13-dev@sha256:ceccc68aa29c03c808090dc4c6156bebc6d4efaea357281ecde306d6451b7428
  SEMVER_MAJOR_MINOR_VERSION: "0.28"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.28.0
  VERSION: 0.28.0
contents:
  packages:
    - '!base-files'
  builds:
    - name: statsd-exporter-go
      uses: dhi.io/golang:1.24.11-debian13-dev@sha256:ceccc68aa29c03c808090dc4c6156bebc6d4efaea357281ecde306d6451b7428
      contents:
        files:
          - url: git+https://github.com/prometheus/statsd_exporter.git#v0.28.0
            checksum: c0a390a2c43f77863278615b47d46e886bdca726
            path: /go/src/github.com/prometheus/statsd_exporter
            spdx:
              name: statsd_exporter
              version: 0.28.0
              packages:
                - name: statsd_exporter
                  purl: pkg:golang/github.com/prometheus/statsd_exporter@0.28.0
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/prometheus/statsd_exporter
          with:
            deps:
              - golang.org/x/crypto@v0.45.0
              - golang.org/x/oauth2@v0.27.0
            download: true
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/prometheus/statsd_exporter
          with:
            ldflags:
              - -X github.com/prometheus/common/version.Version=0.28.0
              - -X github.com/prometheus/common/version.Revision=c0a390a2c43f77863278615b47d46e886bdca726
              - -X github.com/prometheus/common/version.GoVersion=$(go env GOVERSION)
              - -X github.com/prometheus/common/version.GoOS=$(go env GOOS)
              - -X github.com/prometheus/common/version.GoArch=$(go env GOARCH)
              - -X github.com/prometheus/common/version.Branch=main
              - -X github.com/prometheus/common/version.BuildUser=ci@docker-build
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/local/bin/statsd_exporter
            packages: .
      outputs:
        - source: ${target.dir}/usr/local/bin/statsd_exporter
          target: /usr/local/bin/statsd_exporter
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/statsd_exporter
          target: /opt/docker/sbom/statsd_exporter
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
annotations:
  org.opencontainers.image.description: A minimal statsd-exporter image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/local/bin/statsd_exporter
ports:
  - 9102/tcp
