metadata:
  display-name: Prometheus NATS Exporter Helm chart
  short-description: Exports NATS metrics for scraping by Prometheus.
  featured: false
  home-url: https://github.com/prometheus/helm-charts/charts/prometheus-nats-exporter
  categories:
    - monitoring-and-observability
