metadata:
  display-name: Pyroscope
  short-description: Grafana Pyroscope is an open source software project for aggregating continuous profiling data.
  featured: false
  home-url: https://pyroscope.io/
  categories:
    - developer-tools
    - monitoring-and-observability
