# syntax=dhi.io/build:1-debian13

name: Traefik 2.x
image: dhi.io/traefik
variant: runtime
tags:
  - "2"
  - "2.11"
  - 2.11.33
  - 2-debian13
  - 2.11-debian13
  - 2.11.33-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2024-02-12"
  end-of-life: "2026-02-01"
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: 5fe10e2098c67d066b8bde7f4ef97742bc759267
  GOLANG_REFERENCE: dhi/golang:1.24.11-debian13-dev@sha256:3e717c75bdd2e547755fc90963578c5424b77243f4c35f97ac025ca783a41b6a
  GOLANG_VERSION: 1.24.11
  NODE_REFERENCE: dhi/node:22.21.1-debian13-dev@sha256:9f2cc2b28df3ddcbf95208b8bd18df85fdc2ef63fc89b2a8bd2e9ec31731f873
  NODE_VERSION: 22.21.1
  SEMVER_MAJOR_MINOR_VERSION: "2.11"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.11.33
  VERSION: 2.11.33
contents:
  packages:
    - '!libelogind0'
    - '!mawk'
    - '!original-awk'
    - base-files
  builds:
    - name: go
      uses: dhi.io/golang:1.24.11-debian13-dev@sha256:3e717c75bdd2e547755fc90963578c5424b77243f4c35f97ac025ca783a41b6a
      contents:
        packages:
          - grep
          - sed
        files:
          - url: git+https://github.com/traefik/traefik.git#v2.11.33
            checksum: 5fe10e2098c67d066b8bde7f4ef97742bc759267
            path: /go/src/github.com/traefik/traefik/v2
            spdx:
              name: traefik
              version: 2.11.33
              packages:
                - name: traefik
                  purl: pkg:golang/github.com/traefik/traefik@2.11.33#v2
                  license: MIT
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:22.21.1-debian13-dev@sha256:9f2cc2b28df3ddcbf95208b8bd18df85fdc2ef63fc89b2a8bd2e9ec31731f873
            includes:
              - opt/nodejs
              - usr/local/bin
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/traefik/traefik/v2
          with:
            deps:
              - golang.org/x/crypto@v0.45.0
            download: true
        - name: run unit tests
          work-dir: /go/src/github.com/traefik/traefik/v2
          runs: |
            set -eux -o pipefail

            go test -v ./cmd/...
        - name: build traefik
          uses: go/build@v1
          work-dir: /go/src/github.com/traefik/traefik/v2
          with:
            ldflags:
              - -X github.com/traefik/traefik/v2/pkg/version.Version=2.11.33
              - -X github.com/traefik/traefik/v2/pkg/version.Codename=$(grep -Po 'CODENAME \?= \K\w+' Makefile)
              - -X github.com/traefik/traefik/v2/pkg/version.BuildDate=$(date -d @${SOURCE_DATE_EPOCH} +'"%Y-%m-%dT%H:%M:%SZ')
            output: ${target.dir}/usr/local/bin/traefik
            packages: ./cmd/traefik
      outputs:
        - source: ${target.dir}/usr/local/bin/traefik
          target: /usr/local/bin/traefik
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/traefik
          target: /opt/docker/sbom/traefik
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
annotations:
  org.opencontainers.image.description: A minimal traefik image
  org.opencontainers.image.licenses: MIT
entrypoint:
  - /usr/local/bin/traefik
tests:
  - name: Run testcontainers tests
    directory: image/traefik/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
