# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Collector Helm chart 0.x
image: dhi.io/opentelemetry-collector-chart
variant: helm
tags:
  - 0.145.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 8ba8e06485a1ce9fb137b8cfd29f2d8093c8f0ea
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.145.0-debian13@sha256:8bb47a951a208d9c8ad3d67b4d94964cd7a38d44080571d13ad899b3105d3a95
  SEMVER_MAJOR_MINOR_VERSION: "0.145"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.145.0
  VERSION: 0.145.0
contents:
  builds:
    - name: opentelemetry-collector
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-collector-0.145.0
            checksum: 8ba8e06485a1ce9fb137b8cfd29f2d8093c8f0ea
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            chart:
              appRef: opentelemetry-collector
              description: Docker Hardened Images Helm chart for OpenTelemetry Collector
              images:
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.145.0-debian13@sha256:8bb47a951a208d9c8ad3d67b4d94964cd7a38d44080571d13ad899b3105d3a95
              name: opentelemetry-collector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-collector/config
