# syntax=dhi.io/build:2-helm3

name: Azure Service Operator Helm chart 2.x
image: dhi.io/azure-service-operator-chart
variant: helm
tags:
  - 2.17.0
platforms:
  - linux/amd64
vars:
  AZURE_SERVICE_OPERATOR_IMAGE_TAG: 2.17.0
  AZURE_SERVICE_OPERATOR_REFERENCE: dhi/azure-service-operator:2.17.0-debian13@sha256:cd08e7d423beace74912d98019aa950d73285f11662fb40110648c4c378c9734
  CHART_COMMIT_SHA: 47af64b74b8f7f7dcae3d6f5bc6ff274784ca2f3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
  SEMVER_MAJOR_MINOR_VERSION: "2.17"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.17.0
  VERSION: 2.17.0
contents:
  builds:
    - name: azure-service-operator
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/Azure/azure-service-operator.git#v2.17.0
            checksum: 47af64b74b8f7f7dcae3d6f5bc6ff274784ca2f3
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/v2/charts/azure-service-operator/
          with:
            chart:
              appVersion: 2.17.0
              description: Docker Hardened Images Helm chart for Azure Service Operator
              images:
                - name: azure-service-operator
                  ref: dhi/azure-service-operator:2.17.0-debian13@sha256:cd08e7d423beace74912d98019aa950d73285f11662fb40110648c4c378c9734
              name: azure-service-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/Azure/azure-service-operator
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/v2/charts/azure-service-operator/
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/v2/charts/azure-service-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/v2/charts
          with:
            chart: azure-service-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/v2/charts/azure-service-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/azure-service-operator/config
