# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart VERSION:^v?([0-9]+).*$.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.3
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.3-debian13@sha256:7590a4adc74ca4748b33580c515ea825610dff81fcff0948954cb0fa2c163a63
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.3-debian13@sha256:009286ddf29ae19d0f8982b1372a5b3f59864750fbf98974310a4a2be5e64a41
  CERT_MANAGER_COMMIT_SHA: d4faed26ae12115cceb807cdc12507ebc28980e2
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.3-debian13@sha256:b4dff1925be398e7ea25382afae2d5537f7e2c6cda93c73a1002234bf99d964c
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.3-debian13@sha256:cfee5351784b79acfc1071099fdcbf19c868728f7737c74005c0aa82426ca63a
  CERT_MANAGER_VERSION: 1.19.3
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.3-debian13@sha256:a6f76ed8e86dd947752a002372b3cc1bcd7685246f4ecdc6ba2a4fbde38e6e3a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
  SEMVER_MAJOR_MINOR_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+).*$}
  SEMVER_MAJOR_VERSION: ${VERSION:^v?([0-9]+).*$}
  SEMVER_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+\.[0-9]+).*$}
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.3
            checksum: d4faed26ae12115cceb807cdc12507ebc28980e2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.3-debian13@sha256:b4dff1925be398e7ea25382afae2d5537f7e2c6cda93c73a1002234bf99d964c
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.3-debian13@sha256:009286ddf29ae19d0f8982b1372a5b3f59864750fbf98974310a4a2be5e64a41
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.3-debian13@sha256:7590a4adc74ca4748b33580c515ea825610dff81fcff0948954cb0fa2c163a63
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.3-debian13@sha256:cfee5351784b79acfc1071099fdcbf19c868728f7737c74005c0aa82426ca63a
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.3-debian13@sha256:a6f76ed8e86dd947752a002372b3cc1bcd7685246f4ecdc6ba2a4fbde38e6e3a
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
