# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart VERSION:^v?([0-9]+).*$.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.3
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.3-debian13@sha256:521d4f8e7f664016fbc66edb3a7b6a178649039f304b6cb2ffcde32782d41c4e
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.3-debian13@sha256:32490880c60eec7deebf3a7128e1ebb0a7cb79638b897b4042471913c9f291cd
  CERT_MANAGER_COMMIT_SHA: d4faed26ae12115cceb807cdc12507ebc28980e2
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.3-debian13@sha256:32ad7908acd9ada84e34af79cc23dfb205d408aa7fc72e83078e762641f44a73
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.3-debian13@sha256:ee342220dcab607145455dc06525814b10779f2cae2eb082aed0fe8b6529bd0d
  CERT_MANAGER_VERSION: 1.19.3
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.3-debian13@sha256:be39e06f44a939c1ead89ac508b771ad670203db323157486777d55520f6eb20
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
  SEMVER_MAJOR_MINOR_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+).*$}
  SEMVER_MAJOR_VERSION: ${VERSION:^v?([0-9]+).*$}
  SEMVER_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+\.[0-9]+).*$}
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.3
            checksum: d4faed26ae12115cceb807cdc12507ebc28980e2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.3-debian13@sha256:32ad7908acd9ada84e34af79cc23dfb205d408aa7fc72e83078e762641f44a73
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.3-debian13@sha256:32490880c60eec7deebf3a7128e1ebb0a7cb79638b897b4042471913c9f291cd
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.3-debian13@sha256:521d4f8e7f664016fbc66edb3a7b6a178649039f304b6cb2ffcde32782d41c4e
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.3-debian13@sha256:ee342220dcab607145455dc06525814b10779f2cae2eb082aed0fe8b6529bd0d
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.3-debian13@sha256:be39e06f44a939c1ead89ac508b771ad670203db323157486777d55520f6eb20
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
