# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart VERSION:^v?([0-9]+).*$.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.2
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.2-debian13@sha256:40d2977ca12b7b37bbef51826cb2bf7209dd925dde51187c5a22fc71fbd790c8
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.2-debian13@sha256:8f48fad48108682fa3de383369963c8697acf20747af066639affcd9418cb226
  CERT_MANAGER_COMMIT_SHA: 6e38ee57a338a1f27bb724ddb5933f4b8e23e567
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.2-debian13@sha256:83125a2df633b71c6bdc0158097da9c07635cf2ce248123d6977041ac08a5d03
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.2-debian13@sha256:d00f683c50c05b2d5fc5f25e007719d1b360dee36cd5888def373db9b9e64dd3
  CERT_MANAGER_VERSION: 1.19.2
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.2-debian13@sha256:7020013ea15e6abd4fecef252e8a6b0a90a22a328b01811fd7a7e2e4423706a3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
  SEMVER_MAJOR_MINOR_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+).*$}
  SEMVER_MAJOR_VERSION: ${VERSION:^v?([0-9]+).*$}
  SEMVER_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+\.[0-9]+).*$}
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:e634d3d0c4ae9bc6fc4ffb768fd972fd75025208a94e67b49d271cfc910ea847
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.2
            checksum: 6e38ee57a338a1f27bb724ddb5933f4b8e23e567
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.2-debian13@sha256:83125a2df633b71c6bdc0158097da9c07635cf2ce248123d6977041ac08a5d03
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.2-debian13@sha256:8f48fad48108682fa3de383369963c8697acf20747af066639affcd9418cb226
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.2-debian13@sha256:40d2977ca12b7b37bbef51826cb2bf7209dd925dde51187c5a22fc71fbd790c8
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.2-debian13@sha256:d00f683c50c05b2d5fc5f25e007719d1b360dee36cd5888def373db9b9e64dd3
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.2-debian13@sha256:7020013ea15e6abd4fecef252e8a6b0a90a22a328b01811fd7a7e2e4423706a3
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
