# syntax=dhi.io/build:2-debian13

name: Docker 29.x (cli)
image: dhi.io/docker
variant: runtime
flavor: cli
tags:
  - 29-cli
  - 29.2-cli
  - 29.2.1-cli
  - 29-debian13-cli
  - 29.2-debian13-cli
  - 29.2.1-debian13-cli
platforms:
  - linux/amd64
  - linux/arm64
vars:
  BUILDX_COMMIT_SHA: a2675950d46b2cb171b23c2015ca44fb88607531
  BUILDX_VERSION: 0.31.1
  COMMIT_SHA: a5c7197d720daef7d8b9e6174ee78c0743cea166
  COMPOSE_COMMIT_SHA: c428a77111d56683b823a47590eb08de5c59a162
  COMPOSE_VERSION: 5.0.2
  GO_REFERENCE: dhi/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
  SCOUT_CLI_PLUGIN_COMMIT_SHA: 04f8540f76d80dd5bfe89f2a3e91bf3a465679c7
  SCOUT_CLI_PLUGIN_VERSION: 1.19.2
  SEMVER_MAJOR_MINOR_VERSION: "29.2"
  SEMVER_MAJOR_VERSION: "29"
  SEMVER_VERSION: 29.2.1
  VERSION: 29.2.1
contents:
  packages:
    - base-files
    - ca-certificates
    - libc6
  builds:
    - name: buildx
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      work-dir: /go/src/github.com/docker/buildx
      caches:
        - path: /go/pkg/mod
      contents:
        packages:
          - gnu-which
        files:
          - url: git+https://github.com/docker/buildx.git#v0.31.1
            checksum: a2675950d46b2cb171b23c2015ca44fb88607531
            path: /go/src/github.com/docker/buildx
            spdx:
              name: docker-buildx
              version: 0.31.1
              packages:
                - name: buildx
                  purl: pkg:golang/github.com/docker/buildx@0.31.1
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          work-dir: /go/src/github.com/docker/buildx
          privileged: true
          environment:
            GODEBUG: ""
            GOFIPS140: ""
          runs: |
            set -eux -o pipefail

            go get github.com/sigstore/rekor@v1.5.0               # CVE-2026-24117, CVE-2026-23831
            go get github.com/theupdateframework/go-tuf/v2@v2.4.1 # CVE-2026-24686
            go mod tidy
            go mod vendor
        - name: go build
          uses: go/build@v1
          with:
            ldflags:
              - -X github.com/docker/buildx/version.Version=0.31.1
              - -X github.com/docker/buildx/version.Revision=a2675950d46b2cb171b23c2015ca44fb88607531
              - -X github.com/docker/buildx/version.Package=github.com/docker/buildx
            output: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-buildx
            packages: ./cmd/buildx
      outputs:
        - source: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-buildx
          target: /usr/local/libexec/docker/cli-plugins/docker-buildx
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/docker-buildx
          target: /opt/docker/sbom/docker-buildx
          uid: 0
          gid: 0
    - name: compose
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      caches:
        - path: /go/pkg/mod
      contents:
        packages:
          - bash
          - btrfs-progs
          - build-essential
          - ca-certificates
          - libseccomp-dev
          - libtool
          - linux-libc-dev
          - liblvm2-dev
        files:
          - url: git+https://github.com/docker/compose.git#v5.0.2
            checksum: c428a77111d56683b823a47590eb08de5c59a162
            path: /go/src/github.com/docker/compose
            spdx:
              name: docker-compose
              version: 5.0.2
              packages:
                - name: compose
                  purl: pkg:golang/github.com/docker/compose@5.0.2
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: build
          work-dir: /go/src/github.com/docker/compose
          privileged: true
          runs: |
            set -eux -o pipefail

            mkdir -p "${target.dir}/usr/local/libexec/docker/cli-plugins"
            GODEBUG="fips140=on" DESTDIR="${target.dir}/usr/local/libexec/docker/cli-plugins" make build
      outputs:
        - source: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-compose
          target: /usr/local/libexec/docker/cli-plugins/docker-compose
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/docker-compose
          target: /opt/docker/sbom/docker-compose
          uid: 0
          gid: 0
    - name: scout
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      caches:
        - path: /go/pkg/mod
      contents:
        files:
          - url: git+https://github.com/docker/scout-cli-plugin.git#v1.19.2
            checksum: 04f8540f76d80dd5bfe89f2a3e91bf3a465679c7
            path: /go/src/github.com/docker/scout-cli-plugin
            spdx:
              name: scout-cli
              version: 1.19.2
              packages:
                - name: scout-cli
                  purl: pkg:github/docker/scout-cli-plugin@1.19.2
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/docker/scout-cli-plugin
          with:
            deps:
              - github.com/theupdateframework/go-tuf/v2@v2.4.1
              - github.com/sigstore/rekor@v1.5.0
              - github.com/sigstore/sigstore@v1.10.4
            download: true
            replaces:
              - github.com/sigstore/sigstore=github.com/sigstore/sigstore@v1.10.4
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/docker/scout-cli-plugin
          with:
            ldflags:
              - -X github.com/docker/scout-cli-plugin/internal/version.version=1.19.2
              - -X github.com/docker/scout-cli-plugin/internal/version.commit=04f8540f76d80dd5bfe89f2a3e91bf3a465679c7
            output: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-scout
            packages: ./cmd/docker-scout
      outputs:
        - source: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-scout
          target: /usr/local/libexec/docker/cli-plugins/docker-scout
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/scout-cli
          target: /opt/docker/sbom/scout-cli
          uid: 0
          gid: 0
    - name: docker-cli
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      contents:
        packages:
          - bash
          - btrfs-progs
          - build-essential
          - ca-certificates
          - libseccomp-dev
          - libtool
          - linux-libc-dev
          - liblvm2-dev
        files:
          - url: git+https://github.com/docker/cli.git#v29.2.1
            checksum: a5c7197d720daef7d8b9e6174ee78c0743cea166
            path: /go/src/github.com/docker/cli
            spdx:
              name: docker-cli
              version: 29.2.1
              packages:
                - name: docker-cli
                  purl: pkg:golang/github.com/docker/cli@29.2.1
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: build
          work-dir: /go/src/github.com/docker/cli
          runs: |
            set -eux -o pipefail

            export DISABLE_WARN_OUTSIDE_CONTAINER=1
            export LDFLAGS=""
            export CGO_ENABLED=1

            make VERSION="29.2.1" dynbinary

            install -Dm755 build/docker-linux-* "${target.dir}/usr/local/bin/docker"
      outputs:
        - source: ${target.dir}/usr/local/bin/docker
          target: /usr/local/bin/docker
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/docker-cli
          target: /opt/docker/sbom/docker-cli
          uid: 0
          gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: docker
      gid: 2375
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
environment:
  DOCKER_BUILDX_VERSION: 0.31.1
  DOCKER_COMPOSE_VERSION: 5.0.2
  DOCKER_TLS_CERTDIR: /cert
  DOCKER_VERSION: 29.2.1
paths:
  - type: directory
    path: /certs/client
    uid: 0
    gid: 0
annotations:
  org.opencontainers.image.description: A minimal Docker image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - docker
