# syntax=dhi.io/build:1-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.31.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: da81d965d3968a19a3da9286f0993da5cd0866de
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  SEMVER_MAJOR_MINOR_VERSION: "0.31"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.31.0
  VAULT_COMPAT_REFERENCE: dhi/vault:1.21.1-debian13-compat@sha256:d6b89d46b3d37d9a1db6550603cdaa4362f48242186f36bdc7c7ec8cf3fac604
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.0-debian13@sha256:7f4b7f32752ac5fe2ba479f1facfe8d79161f4dfa1379bdf12187e3bd7c53681
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.2-debian13@sha256:2c79c8665af5c892a1cfaa68b083714e07373c8ed81ce3447537b2e443543445
  VAULT_REFERENCE: dhi/vault:1.21.1-debian13@sha256:47dc8d20d3cb600eae555deb85821e11a53a0212292e61e4979e605f7d83e9c1
  VERSION: 0.31.0
contents:
  builds:
    - name: vault
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.31.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.1-debian13@sha256:47dc8d20d3cb600eae555deb85821e11a53a0212292e61e4979e605f7d83e9c1
                - name: vault-compat
                  ref: dhi/vault:1.21.1-debian13-compat@sha256:d6b89d46b3d37d9a1db6550603cdaa4362f48242186f36bdc7c7ec8cf3fac604
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.2-debian13@sha256:2c79c8665af5c892a1cfaa68b083714e07373c8ed81ce3447537b2e443543445
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.0-debian13@sha256:7f4b7f32752ac5fe2ba479f1facfe8d79161f4dfa1379bdf12187e3bd7c53681
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
tests:
  - name: Run vault testcontainers helm tests
    directory: chart/vault/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
