# syntax=dhi.io/build:2-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.32.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 3e032ad7685f80fc2a021e282a52b6d2fbd37a07
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
  SEMVER_MAJOR_MINOR_VERSION: "0.32"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.32.0
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.0-debian13@sha256:a3ce500f083f91919d45927b630e67c5d9309024b950da0e39f61463f2db4714
  VAULT_HELM_REFERENCE: dhi/vault:1.21.2-debian13-helm@sha256:1ec754647575b44d4416226d41e8e6ee7d9dc1c1ad167dc50becba8adf335504
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.2-debian13@sha256:95a802c413e58399c17534e03284478d625cab85e2b03d943aaebefe0b817165
  VAULT_REFERENCE: dhi/vault:1.21.2-debian13@sha256:8b0b549ce80c0e820cc6c0fe90d13cf00cb99d9d195933fb634cb7ec126ba6d7
  VERSION: 0.32.0
contents:
  builds:
    - name: vault
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:71b7163acd69b29d5d2c431646ad54a453b27a9915cce53b4d277796e0dabc79
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.32.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.2-debian13@sha256:8b0b549ce80c0e820cc6c0fe90d13cf00cb99d9d195933fb634cb7ec126ba6d7
                - name: vault-helm
                  ref: dhi/vault:1.21.2-debian13-helm@sha256:1ec754647575b44d4416226d41e8e6ee7d9dc1c1ad167dc50becba8adf335504
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.2-debian13@sha256:95a802c413e58399c17534e03284478d625cab85e2b03d943aaebefe0b817165
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.0-debian13@sha256:a3ce500f083f91919d45927b630e67c5d9309024b950da0e39f61463f2db4714
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
