# syntax=dhi.io/build:2-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.32.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 3e032ad7685f80fc2a021e282a52b6d2fbd37a07
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
  SEMVER_MAJOR_MINOR_VERSION: "0.32"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.32.0
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.0-debian13@sha256:f8929ceffef93b655f166ae4fa5e79c34b1220d20e003f0a1d4ef90f1094eba7
  VAULT_HELM_REFERENCE: dhi/vault:1.21.2-debian13-helm@sha256:822318c78c6b603deaa4f495d27c4955f232897ed1efa5a02d862379fcaeecbd
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.2-debian13@sha256:e206cd2ce26fd173293507d1c48a44c01222557a213c35b8a00b01f26926429c
  VAULT_REFERENCE: dhi/vault:1.21.2-debian13@sha256:faa15eaf4d2d0fbce5fa3270403f95b3e67873fa6efb566d32e5575e7fcf0262
  VERSION: 0.32.0
contents:
  builds:
    - name: vault
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.32.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.2-debian13@sha256:faa15eaf4d2d0fbce5fa3270403f95b3e67873fa6efb566d32e5575e7fcf0262
                - name: vault-helm
                  ref: dhi/vault:1.21.2-debian13-helm@sha256:822318c78c6b603deaa4f495d27c4955f232897ed1efa5a02d862379fcaeecbd
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.2-debian13@sha256:e206cd2ce26fd173293507d1c48a44c01222557a213c35b8a00b01f26926429c
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.0-debian13@sha256:f8929ceffef93b655f166ae4fa5e79c34b1220d20e003f0a1d4ef90f1094eba7
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
