# syntax=dhi.io/build:2-helm3

name: External DNS Helm chart 1.x
image: dhi.io/external-dns-chart
variant: helm
tags:
  - 1.20.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: e951aab3d50cc348bdf1c2bd89baf951d49c573b
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  EXTERNAL_DNS_REFERENCE: dhi/external-dns:0.20.0-debian13@sha256:403ffefca5c45be1f1b47aa9afc00878cce179b4c9f24b5904acced3f9127068
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  SEMVER_MAJOR_MINOR_VERSION: "1.20"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.20.0
  VERSION: 1.20.0
contents:
  builds:
    - name: external-dns
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        files:
          - url: git+https://github.com/kubernetes-sigs/external-dns.git#external-dns-helm-chart-1.20.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/external-dns
          with:
            chart:
              appRef: external-dns
              description: Docker Hardened Images Helm chart for External DNS
              images:
                - name: external-dns
                  ref: dhi/external-dns:0.20.0-debian13@sha256:403ffefca5c45be1f1b47aa9afc00878cce179b4c9f24b5904acced3f9127068
              name: external-dns-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kubernetes-sigs/external-dns
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/external-dns
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/external-dns
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: external-dns
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/external-dns
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/external-dns/config
