# syntax=dhi.io/build:1-helm3

name: External DNS Helm chart 1.x
image: dhi.io/external-dns-chart
variant: helm
tags:
  - 1.19.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b740777701f0684cbc2ab664af3eaa7ec3f7576f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  EXTERNAL_DNS_REFERENCE: dhi/external-dns:0.20.0-debian13@sha256:60514f76bb474a23a75531fda92e640352c3545e384c35afc555b2c33f3298f6
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
  SEMVER_MAJOR_MINOR_VERSION: "1.19"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.19.0
  VERSION: 1.19.0
contents:
  builds:
    - name: external-dns
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:705dc44463a159c5163cc790e19afd3ca2071d63a5c3c7951e4173e1cbb14f0a
      contents:
        files:
          - url: git+https://github.com/kubernetes-sigs/external-dns.git#external-dns-helm-chart-1.19.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/external-dns
          with:
            chart:
              appRef: external-dns
              description: Docker Hardened Images Helm chart for External DNS
              images:
                - name: external-dns
                  ref: dhi/external-dns:0.20.0-debian13@sha256:60514f76bb474a23a75531fda92e640352c3545e384c35afc555b2c33f3298f6
              name: external-dns-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kubernetes-sigs/external-dns
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/external-dns
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/external-dns
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: external-dns
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/external-dns
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/external-dns/config
tests:
  - name: Run external-dns testcontainers helm tests
    directory: chart/external-dns/tests
    commands:
      - go test . -count=1 -v
    exit-code: 0
  - name: Run base helm tests
    directory: test/go-testing/k8s/helm/base
    commands:
      - go test . -count=1 -v
    exit-code: 0
