# syntax=dhi.io/build:2-helm3

name: Prometheus Pushgateway Helm chart 3.x
image: dhi.io/pushgateway-chart
variant: helm
tags:
  - 3.6.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: a5e8b56cc73ec4f8f16b23c1719e041425e25cfe
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:bbd34d906c2bce0070a2daa2c7858393feb6c51862fb139a6e1afc923b6e15b0
  PUSHGATEWAY_REFERENCE: dhi/pushgateway:1.11.2-debian13@sha256:585a2f4b4f10857d5ad41378a2b63f0fc476c27acca6bae1b3b32ebc4a6d14e8
  SEMVER_MAJOR_MINOR_VERSION: "3.6"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.6.0
  VERSION: 3.6.0
contents:
  builds:
    - name: prometheus-pushgateway-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:bbd34d906c2bce0070a2daa2c7858393feb6c51862fb139a6e1afc923b6e15b0
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-pushgateway-3.6.0
            checksum: a5e8b56cc73ec4f8f16b23c1719e041425e25cfe
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-pushgateway
          with:
            chart:
              appRef: pushgateway
              description: Docker Hardened Images Helm chart for Prometheus Pushgateway
              images:
                - name: pushgateway
                  ref: dhi/pushgateway:1.11.2-debian13@sha256:585a2f4b4f10857d5ad41378a2b63f0fc476c27acca6bae1b3b32ebc4a6d14e8
              name: pushgateway-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-pushgateway
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-pushgateway
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-pushgateway
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-pushgateway
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/pushgateway/config
