# syntax=dhi.io/build:2-helm3

name: Argo Rollouts Helm chart 2.x
image: dhi.io/argo-rollouts-chart
variant: helm
tags:
  - 2.40.6
platforms:
  - linux/amd64
vars:
  ARGO_ROLLOUTS_REFERENCE: dhi/argo-rollouts:1.8.4-debian13@sha256:311a0e762dee8dc782986632f382db056561461e1c6f337f926103ca760b8025
  CHART_COMMIT_SHA: e353ad43221b199169a9e8f0d72fd8ca90b80e0c
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBECTL_ARGO_ROLLOUTS_REFERENCE: dhi/kubectl-argo-rollouts:1.8.4-debian13@sha256:16490ea5c8759406f47ca12f9e9a00555e88671ec6d9914c5697e4af253e05fb
  SEMVER_MAJOR_MINOR_VERSION: "2.40"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.40.6
  VERSION: 2.40.6
contents:
  builds:
    - name: argo-rollouts
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/argoproj/argo-helm#argo-rollouts-2.40.6
            checksum: e353ad43221b199169a9e8f0d72fd8ca90b80e0c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/argo-rollouts
          with:
            chart:
              appRef: argo-rollouts
              dependencies: null
              description: Docker Hardened Images Helm chart for Argo Rollouts
              images:
                - name: argo-rollouts
                  ref: dhi/argo-rollouts:1.8.4-debian13@sha256:311a0e762dee8dc782986632f382db056561461e1c6f337f926103ca760b8025
                - name: kubectl-argo-rollouts
                  ref: dhi/kubectl-argo-rollouts:1.8.4-debian13@sha256:16490ea5c8759406f47ca12f9e9a00555e88671ec6d9914c5697e4af253e05fb
              name: argo-rollouts-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/argoproj/argo-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/argo-rollouts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: argo-rollouts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: argo-rollouts
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: argo-rollouts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/argo-rollouts/config
