# syntax=dhi.io/build:2-helm3

name: Sealed Secrets Helm chart 0.x
image: dhi.io/sealed-secrets-chart
variant: helm
tags:
  - 0.34.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: fd30a3eb590170d99e5d62df254d097a2c131144
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
  SEALED_SECRETS_REFERENCE: dhi/sealed-secrets-controller:0.34.0-debian13@sha256:c2b0008967c05af36d5afcd2168fa3faf4fd6617855dcdfa6b6662907c426aac
  SEMVER_MAJOR_MINOR_VERSION: "0.34"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.34.0
  VERSION: 0.34.0
contents:
  builds:
    - name: sealed-secrets-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:8ae259169a30387938ec0314da8084fd0c74a3726412e78e852205ab043a2673
      contents:
        files:
          - url: git+https://github.com/bitnami-labs/sealed-secrets.git#v0.34.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm/sealed-secrets
          with:
            chart:
              appRef: sealed-secrets-controller
              description: Docker Hardened Images Helm chart for Sealed Secrets
              images:
                - name: sealed-secrets-controller
                  ref: dhi/sealed-secrets-controller:0.34.0-debian13@sha256:c2b0008967c05af36d5afcd2168fa3faf4fd6617855dcdfa6b6662907c426aac
              name: sealed-secrets-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/bitnami-labs/sealed-secrets
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm/sealed-secrets
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          secrets:
            - id: docker_hub_user
              env: DOCKER_HUB_USER
            - id: docker_hub_password
              env: DOCKER_HUB_PASSWORD
          with:
            chart: ${source.dir}/helm-charts/helm/sealed-secrets
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm
          with:
            chart: sealed-secrets
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/helm/sealed-secrets
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/sealed-secrets/config
