# syntax=dhi.io/build:2-helm3

name: Neo4j Helm chart 5.x
image: dhi.io/neo4j-chart
variant: helm
tags:
  - 5.26.21
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 11399cbfd3579e54c80e68359af30739d2bf26ef
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:26b1f5b127ca6fa7ca1aacb8dc39e6d5cd70f20ded2810c8cdd23210342c10ca
  NEO4J_REFERENCE: dhi/neo4j:5.26.21-debian13@sha256:4a46ca734b2d0e12b1914f1b124a7fbcef308d9c8b9361a2358c60aad00558b5
  SEMVER_MAJOR_MINOR_VERSION: "5.26"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.26.21
  VERSION: 5.26.21
contents:
  builds:
    - name: neo4j
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/neo4j/helm-charts.git#5.26.21
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/neo4j
          with:
            chart:
              appRef: neo4j
              description: Docker Hardened Images Helm chart for Neo4j
              images:
                - name: neo4j
                  ref: dhi/neo4j:5.26.21-debian13@sha256:4a46ca734b2d0e12b1914f1b124a7fbcef308d9c8b9361a2358c60aad00558b5
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:26b1f5b127ca6fa7ca1aacb8dc39e6d5cd70f20ded2810c8cdd23210342c10ca
              name: neo4j-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/neo4j/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/neo4j
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/neo4j
            cmd: dependency update
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/neo4j
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for neo4j-operations
            sed -i '/- name: .*-operations/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/neo4j-operations.yaml
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: neo4j
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/neo4j
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/neo4j/config
