# syntax=dhi.io/build:2-helm3

name: Neo4j Helm chart 5.x
image: dhi.io/neo4j-chart
variant: helm
tags:
  - 5.26.19
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 9e167874715a2f056ce3195ff229a05b2bb69ab0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:e070764f05422fb706323120ef5a182eb965d69ecb8f634f506c4ac2c0952087
  NEO4J_REFERENCE: dhi/neo4j:5.26.20-debian13@sha256:cb4b9f461c5ab967e95d80c616cff63995aec8f9c90d2633390709a9635ee8cd
  SEMVER_MAJOR_MINOR_VERSION: "5.26"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.26.19
  VERSION: 5.26.19
contents:
  builds:
    - name: neo4j
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
      contents:
        files:
          - url: git+https://github.com/neo4j/helm-charts.git#5.26.19
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/neo4j
          with:
            chart:
              appRef: neo4j
              description: Docker Hardened Images Helm chart for Neo4j
              images:
                - name: neo4j
                  ref: dhi/neo4j:5.26.20-debian13@sha256:cb4b9f461c5ab967e95d80c616cff63995aec8f9c90d2633390709a9635ee8cd
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:e070764f05422fb706323120ef5a182eb965d69ecb8f634f506c4ac2c0952087
              name: neo4j-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/neo4j/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/neo4j
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/neo4j
            cmd: dependency update
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/neo4j
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for neo4j-operations
            sed -i '/- name: .*-operations/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/neo4j-operations.yaml
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: neo4j
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/neo4j
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/neo4j/config
