# syntax=dhi.io/build:2-debian13

name: Helm 4.x (dev)
image: dhi.io/helm
variant: dev
tags:
  - 4-dev
  - 4.1-dev
  - 4.1.1-dev
  - 4-debian13-dev
  - 4.1-debian13-dev
  - 4.1.1-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: 5caf0044d4ef3d62a955440272999e139aafbbed
  GOLANG_REFERENCE: dhi/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
  SEMVER_MAJOR_MINOR_VERSION: "4.1"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.1.1
  VERSION: 4.1.1
  YQ_REFERENCE: dhi/pkg-go-yq:4.52.2-debian13@sha256:bddaffbb102c3ae329cefa58e05eeb3750200d69ed5bd5ea7ba40f21ddafef09
  YQ_VERSION: 4.52.2
contents:
  packages:
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - base-files
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - util-linux
  builds:
    - name: helm
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      work-dir: /go/src/github.com/helm/helm
      contents:
        packages:
          - sed
        files:
          - url: git+https://github.com/helm/helm.git#v4.1.1
            checksum: 5caf0044d4ef3d62a955440272999e139aafbbed
            path: /go/src/github.com/helm/helm
            spdx:
              name: helm
              version: 4.1.1
              packages:
                - name: helm
                  purl: pkg:golang/helm.sh/helm/v3@4.1.1
                  license: Apache-2.0
            uid: 65532
            gid: 65532
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          with:
            deps: []
            download: true
        - name: build
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            ldflags:
              - -X helm.sh/helm/v4/internal/version.version=4.1.1
              - -X helm.sh/helm/v4/internal/version.gitCommit=5caf0044d4ef3d62a955440272999e139aafbbed
              - -X helm.sh/helm/v4/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v4/internal/version.metadata=
            output: ${target.dir}/usr/local/bin/helm
            packages: ./cmd/helm
      accounts:
        run-as: nonroot
        users:
          - name: nonroot
            uid: 65532
            gid: 65532
        groups:
          - name: nonroot
            gid: 65532
            members:
              - nonroot
      outputs:
        - source: ${target.dir}/usr/local/bin
          target: /usr/local/bin
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/helm
          target: /opt/docker/sbom/helm
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/pkg-go-yq:4.52.2-debian13@sha256:bddaffbb102c3ae329cefa58e05eeb3750200d69ed5bd5ea7ba40f21ddafef09
      includes:
        - opt/docker/sbom/yq
        - usr/local/bin/yq
      uid: 0
      gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /workspace
environment:
  DEBIAN_FRONTEND: noninteractive
paths:
  - type: directory
    path: /workspace
    uid: 65532
    gid: 65532
    mode: "0755"
annotations:
  org.opencontainers.image.description: A minimal Helm image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - helm
cmd:
  - help
